### ISSUE TITLE
Web gui

### ISSUE THREAD

**Issue by sidomir7** [mitre/caldera#114]
Hi I installed caldera it is running but, web gui plugin is new ?
I would like to use old web gui like in this video https://youtu.be/xjDrWStR68E
It is possible ? Or i install something wrong ?
When I access localhost:8888 I can see black screen I log in and the I see avaliable plugins by default 4 then I can click on web gui plugin and it works, but I think old gui or at least gui presented on video is better. Is thrre a way how to us it?

Thak you.

**Comment by privateducky** [comment]
Hi @sidomir7 thanks for the feedback. in v2.0, we've replaced the GUI with the dark theme. we are planning on updating our YouTube demo videos to be current (not sure a date yet). 

In the new UI, after logging in, you should click into the 'chain mode' plugin and from there you can use the ribbon to manage operations.

we did the UI swap between 1.0 and 2.0 for a few reasons:
- the JavaScript was tied to the backend Mongo database, resulting in heavy coupling throughout the app. this was the biggest kicker. 
- the D3 force-directed-graph slowed down the app (because of the coupling) when there were too many agents connected to the system. 
- we wanted to swap from a relatively obscure framework (knockout.js) for more standard jquery/ajax. 

let me know what you liked about the previous UI vs the current. this is an area we'll be encouraging others to create additional UI's by creating plugins. the modular framework allows you to replace the UI with a new one if you'd like, without the risk of modifying the core code base.

**Comment by ohmygord** [comment]
@privateducky After login to the new GUI, should all 4 items be accessible (Stockpile, Sandcat, GUI, Chain). 

On mine I can click through to Sandcat, and Chain. Just wanted to ensure everything is correct before going any further. 

If all I need is to go through Chain as per the above, then everything is looking good.

Appreciate the help!
