### ISSUE TITLE
[Testing Response Plugin] : ERROR (data_svc.py:347 _verify_ability_set) Fix technique ID for ability

### ISSUE THREAD

**Issue by Cyb3rWard0g** [mitre/caldera#1480]
Good evening Caldera team,

I am testing some of the plugins with the latest caldera build and I got the following error messages while starting the server:

```
2020-04-05 04:12:39 - ERROR (data_svc.py:347 _verify_ability_set) Fix technique ID for ability: 13d0d9cf-e31a-47b6-9217-f38e3f7c25ef
2020-04-05 04:12:39 - ERROR (data_svc.py:347 _verify_ability_set) Fix technique ID for ability: 13d0d9cf-e31a-47b6-9217-f38e3f7c25ef
2020-04-05 04:12:39 - ERROR (data_svc.py:347 _verify_ability_set) Fix technique ID for ability: 90418255-b202-4fc3-b0ea-b105bff39ca5
2020-04-05 04:12:39 - ERROR (data_svc.py:347 _verify_ability_set) Fix technique ID for ability: 90418255-b202-4fc3-b0ea-b105bff39ca5
```

I looked for those GUID values inside of the /usr/src/app path after building Caldera with all the plugins and those GUIDs pointed to two `Response` plugin files.

```
caldera@3c9a55045fa1:/usr/src/app$ grep -R "13d0d9cf-e31a-47b6-9217-f38e3f7c25ef" .

./plugins/response/data/adversaries/f61e3fc0-43d8-4b36-b5d3-710610b92974.yml:  - 13d0d9cf-e31a-47b6-9217-f38e3f7c25ef
./plugins/response/data/abilities/detection/13d0d9cf-e31a-47b6-9217-f38e3f7c25ef.yml:- id: 13d0d9cf-e31a-47b6-9217-f38e3f7c25ef
```
```
caldera@3c9a55045fa1:/usr/src/app$ grep -R "90418255-b202-4fc3-b0ea-b105bff39ca5" .

./plugins/response/data/adversaries/f61e3fc0-43d8-4b36-b5d3-710610b92974.yml:  - 90418255-b202-4fc3-b0ea-b105bff39ca5
./plugins/response/data/abilities/detection/90418255-b202-4fc3-b0ea-b105bff39ca5.yml:- id: 90418255-b202-4fc3-b0ea-b105bff39ca5
```

I can see that those two detection files have the key `attack_id` value with an empty string.

https://github.com/mitre/response/blob/226eec83a4f63c1d3d406e9eec58337248857644/data/abilities/detection/13d0d9cf-e31a-47b6-9217-f38e3f7c25ef.yml#L8

It makes sense that those two detection abilities do not have an attack ID. It is simply querying logs, but it would be good to coordinate with the `Response` plugin team to maybe add something to it that the https://github.com/mitre/caldera/blob/082bfea232c563b14d14b8216b793815aaff476c/app/service/data_svc.py#L347 script can handle and not just throw an error when it is evaluating technique IDs from Response abilities. I was thinking on creating this issue in the Response plugin repo, but I figured the error handling is done at the Caldera server side. 

Thank you for the awesome project! I am integrating it with several of my tools and lab deployments :)

**Comment by privateducky** [comment]
thanks! I've been meaning to circle back on this actually, as I noticed the same thing after we updated our response plugin the other day. 

there's two things here:

1. we should log this as a WARNING instead of an ERROR, as this has no negative consequence on the server
2. we should give those 2 ability YML files, in the response plugin, an attack_id - even if it's made up for now. when we initially load the data on server boot, we validate each ability file to ensure it is formatted correctly, contains appropriate data, etc., and one of those checks is that there is an attack_id. This is important because we may want to filter on it from the UI. If an ability file is missing this field, we fill in one as "(auto-generated)".

I'll fix #1 on my next PR up. If you want to take a stab at #2, go ahead and push up a PR to the response plugin. Otherwise, we'll try to circle back on that next week.

**Comment by Cyb3rWard0g** [comment]
Thank you @privateducky ! :) I like option one. Option two maybe is already being done? something similar to this?

https://github.com/mitre/response/blob/master/data/abilities/response/02fb7fa9-8886-4330-9e65-fa7bb1bc5271.yml#L8

the script only checks if an ID has been provided, but does not validate if it is a legitimate ATT&Ck ID?

**Comment by privateducky** [comment]
exactly. I went ahead and did #1 (swapped to a WARNING instead of ERROR log). 

for #2, that's exactly what we'd want. feel free to propose a PR for that. the reason we don't validate ATT&CK techniques, is to leave it flexible for people with their own categorization (or extension of attack). we just care that they have something there-- whether it is valid ATT&CK or not.

**Comment by Cyb3rWard0g** [comment]
Thank you for doing that! Regarding option 2, it makes sense to leave it flexible. Ok I will add an X to the ones triggering the WARNING logic following a similar approach taken on other response abilities and then submit a PR. Thank you @privateducky ! 👍
