### ISSUE TITLE
Impossible to invoke Mimikatz

### ISSUE THREAD

**Issue by g4laad** [mitre/caldera#151]
Good morning,

I'm trying Caldera. I would like to use run Mimikatz however, it seems that the file is not sent to the agent.
When I add one of these abilities to an adversary, I have a red circle:
![image](https://user-images.githubusercontent.com/11516870/58080881-4e547b80-7bb4-11e9-9721-4184d15d62f0.png)

Setup:
server: Kali linux 2019, using a python3 venv
agent: W10, PowerShell 5.1

Thank you

**Comment by privateducky** [comment]
good find-- we had the incorrect server variable set inside those two variables. they were set to #{caldera} instead of #{server}. note the change here:
https://github.com/mitre/stockpile/compare/8b9a38346139adf9cb0a6f9f761eeee1e24ed788...14a655f441ef46e6f133fb062e3e9d964b304691#diff-a8d15452fbb62d90882b86ed4c6f159f
Let me know if you have any other issues with it.
