### ISSUE TITLE
No abilities shown in the GUI

### ISSUE THREAD

**Issue by g4laad** [mitre/caldera#159]
The abilities do not show on the GUI anymore.
Wild guess: the system of session appeared and with that new IDs. Maybe it's not synced with the GUI.

![image](https://user-images.githubusercontent.com/11516870/58336151-79a0ca00-7e43-11e9-99a2-fc27eaf2c175.png)

**Comment by khyberspache** [comment]
Thanks for the heads up.  @privateducky will be pushing a patch shortly with some updated terminal code.

**Comment by privateducky** [comment]
@g4laad the issue was due to 3 abilities being added to the stockpile database without descriptions (the field was null). I have since corrected these 3 abilities and retested. I'll make a note that we need to add a validation check when loading abilities to make sure all fields contain a valid input. thanks!
