### ISSUE TITLE
Missing phases in adversaries panel.

### ISSUE THREAD

**Issue by diwakkarsp** [mitre/caldera#1597]
On my caldera server, missing to see the phases in the adversaries panel in the GUI. here is the screenshot. Could you please help.

![image](https://user-images.githubusercontent.com/64507237/80549931-7df73080-898c-11ea-967b-13908dd62f99.png)

**Comment by khyberspache** [comment]
@diwakkarsp We've actually made a (major) refactoring to the to the planning engine of Caldera, and this is part of it.  If you notice in the top left corner of the ability boxes, there is a number that indicates the "atomic order" those abilities will be executed in.  That is functionally equivalent to phases - just order the abilities via drag and drop into a similar order they would have been in for phases.

The change was made in order to set the stage for more powerful autonomous planners. For example, the new structure will allow the planner to _automatically_ group an adversary's abilities into "buckets" that match typical adversary behavior (initial access, remote reconnaissance, local recon, lateral movement, etc).  From there we can perform "macro" planning about which state the adversary should be in and how it should select abilities to reach those states.

**Comment by diwakkarsp** [comment]
@khyberspache Thank you. for your quick response.
