### ISSUE TITLE
Inconsistent terminology: Aversary vs Profile and Abillities vs Links

### ISSUE THREAD

**Issue by clr2of8** [mitre/caldera#1875]
It is confusing throughout the Caldera web interface that Adversaries are mostly referred to as adversaries but sometimes as Profiles. Same issue with Abilities vs Links.

**Comment by slickjitz** [comment]
Profiles are made up of one or more adversaries. Adversaries are made up of one or more abilities. Also I am fairly certain Links are synonymous with agents, at least within the context of an operation form what I have seen. The terminology has taken me quite a lot of time to grasp as well.

**Comment by unkempthenry** [comment]
Hey, sorry about the confusion.  

Here's a link to our docs that cover a fair amount of the terminology we use https://caldera.readthedocs.io/en/latest/Learning-the-terminology.html . 

I'll admit, we're a bit inconsistent with "Adversary" and "Profile."  "Adversaries" is the most official name, but we'll frequently refer to them as "Adversary Profiles" probably because we think that it's more descriptive and less confusing in some cases: for instance, we might say that we created an "adversary profile" (set of caldera abilities) based on an actual adversary (person/threat group). For the most part, "Adversary," "Profile" and "Adversary Profile" can be treated as interchangeable.

There is actually an important distinction between "Ability" and "Link".  Abilities are flexible templates of commands and Links are the solid instantiations of the commands.  When caldera is executing an adversary (a group of abilities) it does so by creating Links from the ability-templates and dispatching them to agents.  A Link is an ability after it's been tasked to a specific agent, selected an execution method (powershell, sh, etc), and had any variables filled in with facts. You can probably get away with equating the two in most cases, but the distinction becomes important if you're trying to do something custom like developing your own plugin for Caldera.  In case it helps, the term "Link" came about from the idea of there being a "chain" of activity -- each action taken by an agent is a "link" in this chain.

Summary: 

Agents = Implants/RATs/bits of code running on a target system that allow execution of links. Agents are also members of "groups," which are useful if you only want to only let Caldera execute on some agents and not others.
Abilities = Templates that describe an action.
Links = The action that will be performed. Each one is specific to an agent and generated from abilities during caldera's operation. Links can vary based on the target OS, available software, and the "facts" that Caldera knows about. 
Adversary Profiles = Groups/sets of abilities.

**Comment by clr2of8** [comment]
Awesome, thank you so much for the info!
