### ISSUE TITLE
Thief profile and how #{file.sensitive.extension} works (v2.7.0)

### ISSUE THREAD

**Issue by slickjitz** [mitre/caldera#1877]
I am trying to full determine how the Thief profile works and in the "Find files" adversary (technique T1005- Data from Local System) in the powershell command we see it uses:

 `Get-ChildItem C:\Users -Recursive -Include *.#{file.sensitive.extension}`....

I am not super experienced in powershell but I am assuming this #{file.sensitive.extension} is some sort of variable. Does anyone know what file extensions Mitre has determined "sensitive"? Thanks

**Comment by unkempthenry** [comment]
Hi @slickjitz , 

Variables expressed like `#{<some name>}` are actually filled in by caldera before dispatching the command to an agent. The values are facts that are either pre-configured in the "sources" view of the web interface or learned by executing other abilities. You can use the sources view to create a source that has the extensions you care about and then select it when you start an operation. The built-in 'basic' source will look for `.png`, `.wav` and `.yml`(these extensions are there more as examples, not because we think these are the file-types that typically hold sensitive information).  

Here are some links to our docs that cover this in a bit more detail:

Abilities: https://caldera.readthedocs.io/en/latest/Learning-the-terminology.html#what-is-an-ability 
Facts: https://caldera.readthedocs.io/en/latest/Learning-the-terminology.html#what-is-a-fact 
Sources: https://caldera.readthedocs.io/en/latest/Learning-the-terminology.html#what-is-a-source

**Comment by wbooth** [comment]
Thanks @unkempthenry , @slickjitz if you still have more questions feel free to re-open this issue or start a new one
