### ISSUE TITLE
User Add #18 Exercise Gets 500 error

### ISSUE THREAD

**Issue by aldo1901** [mitre/caldera#1885]
Trying to complete exercise #18 Add New user. I can edit the default.yaml with test:test, but when I try to log in with those creds I get a 500 error.Caldera log say test logged in, just like with the red account. It only happens with the test account. I added blue:blue and that worked.

Any thought? Thanks

**Comment by garunagiri** [comment]
Can you paste the contents of your default.yml here please? And to confirm, you're using the '--insecure' flag when starting Caldera? And lastly, are you changing the config file after you've shut down the server (you should be)?

**Comment by aldo1901** [comment]
Yes. I am only making changes to the config after stopping the server and I am using the --insecure flag.

exfil_dir: /tmp
host: 0.0.0.0
plugins:
- access
- atomic
- compass
- debrief
- fieldmanual
- gameboard
- manx
- response
- sandcat
- stockpile
- training
port: 8888
reports_dir: /tmp
requirements:
  go:
    command: go version
    type: installed_program
    version: 1.11
  python:
    attr: version
    module: sys
    type: python_module
    version: 3.6.1
users:
  blue:
    blue: admin
  red:
    admin: admin
    red: admin
  test:
    test: test

**Comment by garunagiri** [comment]
I think I see the issue. The higher level 'red' and 'blue' keys refer to user contexts rather than user keys. So when you add a 'test:' value in line with 'red:' and 'blue:', you're attempting to specify an entirely different user type rather than just a new user. The intended goal here is to add just a new user within the 'red:' key. Your default.yml would then look like this:

users:
  blue:
    blue: admin
  red:
    admin: admin
    red: admin
    test: test

Hope that helps!

**Comment by aldo1901** [comment]
Oh wow. I feel stupid. Yes. I did not consider that. It works now. Thank You

**Comment by garunagiri** [comment]
All good! It can be a little confusing : )
