### ISSUE TITLE
Plugin that mimics fake page ( Phishing simulation)

### ISSUE THREAD

**Issue by pierrickboulanger** [mitre/caldera#1964]
Hi ,
I remenmber a plugin/feature that was generating a fake page to display a download button to get the Sandcat agent.
It was bundled with a webpage copier.
I cannot find it anymore it seems that feature was disabled, I forgot the release tag.
Can someone help me figure it out ?
I thought it was the builder but now I'm not sure.
I reckon that it was very useful and it was generating nice logs on the proxy, to correlate with  dropper downloads from phishing emails etc...

Thank you !

**Comment by tobesr** [comment]
I'm looking for this as well - looking back through the release notes it appears to have been moved to the access plugin in version 2.6.0, but I think I remember it existing before that.  In fact I might remember it being removed at one point around 2.3, but cant really remember.

**Comment by pierrickboulanger** [comment]
@tobesr Thank you so much ! Do you happen to know what it has been removed ? It helped me a lot while I was Testing user behavior rules on carbon black for initial compromise. Much better an realistic than than the "deploy agent" long powershell command in my opinion.

**Comment by tobesr** [comment]
@pierrickboulanger No idea sorry - i'm not part of the project and (unfortunately) have not paid particularly close attention for the last year. I was looking for it to demo a phishing email then initial beacon for some training I am running in Feb. Version 2.3.0 despite including the functionality didn't work out the box (couldn't easily change the IP/port for the web beacon).  

@privateducky might know how the access plugin does it / if it can do it?

**Comment by privateducky** [comment]
@tobesr i can definitely help! The drive-by download did indeed shift around between the versions noted here. I'm afk but will find this for you tomorrow.

A second, similar functionality is the weather page. If you go to: 0.0.0.0/weather you'll see a generic webpage. If you type "caldera" (anywhere) the page will disappear and you'll have a new agent available. This is great for physical pen testing. Additionally, the ragdoll python agent will scrape instructions from DOM elements off this page during an operation, if you use it.

By the way, @khyberspache and myself are supporting a new C2 called Operator, which does a ton of realistic traffic generation, if that's what you're looking for!

**Comment by privateducky** [comment]
@pierrickboulanger ok dug it up for you. you can find it in the 2.3.0 version.

after logging in, head to the Sandcat tab and you'll see a website cloning option at the bottom. Clicking the big arrow will take you to the cloned site. Otherwise, replace the cloned site with your own, using the input box (you could clone https://example.com, for example). Then click the arrow to verify you cloned correctly.

<img width="1410" alt="Screen Shot 2020-12-24 at 6 57 04 AM" src="https://user-images.githubusercontent.com/49954156/103087368-41301780-45b5-11eb-8f75-8a69783db917.png">

Any visitor to the cloned site will, by default, have a drive-by download of Sandcat occur on their computer. The malicious.js module is what controls that, in case you want to replicate elsewhere.

**Comment by privateducky** [comment]
I noticed one of my responses to this issue was deleted. I gave two valid answers to @pierrickboulanger and @tobesr (I happen to know this area of code well, as I wrote it) in separate comments but one was deleted. Can you supply some context as to why?

**Comment by wbooth** [comment]
@privateducky appreciate the thorough answer, like most communities -- no advertising or blog spam

**Comment by privateducky** [comment]
@wbooth I answered the question and notified @tobesr and @pierrickboulanger that I'm working on a different project now - I didn't link or even explicitly give any information other than a name. That's not advertising and it's unfair to remove my comment informing a community member that I'm not working on this project anymore. 

An open-source project, by definition, should be open to all communication and challenging of code and ideas. I appreciate not allowing explicit spam of projects but this is not that. I was explicitly asked for feedback on the stated problem. I answered, supplying both answers from within the Caldera framework as well as external considerations for the user, as the sharing of ideas and information fuels open-source communities like this.

As an aside, this issue was open for 17 days - unanswered - before I commented. As the designer of this project, I simply wanted the user to know I personally wasn't ignoring him but that I am supporting work elsewhere and as such, I'm not watching this board consistently. 

I would suggest that you allow free and open discussion on this project, otherwise it dilutes the value a great project like this can have.

**Comment by pierrickboulanger** [comment]
Thank you so much @privateducky I'm going to keep that release in my bookmark.
It is indeed true that this question was long left unanswered. Thanks again for your help.
I think this question can be closed.

I wish all all happy new year.
