### ISSUE TITLE
Running CAGENT.EXE using Domain User (not local admin)

### ISSUE THREAD

**Issue by c0d3xpl0it** [mitre/caldera#20]
Team,

Kudos for awesome project. I am facing some challenges starting cagent.exe from domain user with normal privileges.

**Being normal domain user, we cannot start the new service. (Error)**
```
C:\Program Files\cagent>cagent.exe --startup auto install
Installing service cagent
Error installing service: Access is denied. (5)
```
**Trying cagent.exe under a domain users context (Error)**
```
C:\Program Files\cagent>cagent.exe --username hackable\victim1 --password Victim@1 start
Starting service cagent
Error starting service: Access is denied.
```
**Debugging cagent.exe under a domain users context (Error)**
```
C:\Program Files\cagent>cagent.exe --username hackable\victim1 --password Victim@1 debug
Debugging service cagent - press Ctrl+C to stop.
Info 0x400000FF - Created WinSvcLogHandler
Info 0x40001002 - The cagent service has started.
Error 0xC00000FF - ERROR:caldera_agent.async_client:Caught unhandled exception while running job:
Traceback (most recent call last):
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\async_client.py", line 117, in run_job
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\interfaces.py", line 64, in run
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\interfaces.py", line 108, in _write_commander
PermissionError: [Errno 13] Permission denied: 'C:\\commander.exe'
```
All above check were performed using "**Active User**" option.

![image](https://user-images.githubusercontent.com/8144002/36015444-de274018-0d87-11e8-83b6-eab97d796851.png)

I also tried scenario running cmd with Admin privileges on client end and on Caldera server with Starting user as "Active User" option, got below error.
```
C:\Program Files\cagent>cagent.exe --username hackable\victim1 --password Victim@1 debug
Debugging service cagent - press Ctrl+C to stop.
Info 0x400000FF - Created WinSvcLogHandler
Info 0x40001002 - The cagent service has started.
Error 0xC00000FF - ERROR:caldera_agent.async_client:Caught unhandled exception while running job:
Traceback (most recent call last):
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\async_client.py", line 117, in run_job
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\interfaces.py", line 94, in run
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\interfaces.py", line 141, in _create_process_as_active_user
pywintypes.error: (1314, 'WTSQueryUserToken', 'A required privilege is not held by the client.')
```
But if I start cagent.exe service  with Administrator privileges (on client) and on Caldera Server with Starting user as SYSTEM, everything runs **smooth**. But this wont be scenario in actual corporate environment. Also every domain user cannot be local admin.

Please guide me, if I am missing anything or ideal way to test in corporate environment.

**Comment by hf-mitre** [comment]
@c0d3xpl0it cagent is designed to run as a Windows service so it requires admin privileges to be installed.  When running an operation, RATs (these are distinct processes from cagent) can be run without admin privileges (though this restricts the techniques that can be used unless the RATs can successfully execute a technique that elevates their privileges).  It is possible to start cagent from an un-elevated account by running `cagent.exe debug`, however this was never intended to be an option for running operations, so your mileage will definitely vary. 

RATs communicate with the server via an installed cagent service.  We went this way partially because it limits the scope of an operation to hosts with cagent installed (caldera won't move to hosts that don't have cagent installed on them).

**Comment by hf-mitre** [comment]
I believe what caused the `Permission Denied` error when you ran cagent in debug mode was because the user didn't have write permissions to C:\ -- you could try changing the start path to a directory in the user's home directory.  That said, we don't have any plans to support running cagent w/o admin privileges so something else could very likely break =/

**Comment by dm-mitre** [comment]
@hledger If you have a commander already running, then you'll want to select the Start Method option to "Existing Rat" when you're creating an operation. I'm guessing you left the default option ("Bootstrap Rat") selected which tries to write commander to disk and start it running, but it can't overwrite commander.exe if its already running as a process. Alternatively you could stop the running commander process and let CALDERA start it for you. We could probably make this error read better, but if you try to the methods I listed things should work better for you.
