### ISSUE TITLE
Automated Red Teaming as a Planning Problem

### ISSUE THREAD

**Issue by wyc7** [mitre/caldera#2009]
Hi, CALDERA Contributors!
    I recently read in detail three papers on CALDERA published by your team: “Intelligent, Automated Red Team Emulation”, "Analysis of Automated Adversary Emulation Techniques" and "Automated Adversary Emulation: A case for Planning and Acting with Unknowns". I am very interested in the two points mentioned in the papers: first the heuristic algorithm(action-preference mapping score), and then the steps of how the planning agent handles uncertainty( Visualization of internal LAVA operation). But I don’t seem to find the source code of the relevant content in the CALDERA project. Can you help me?

**Comment by aapplebaum** [comment]
Hey! Thanks for reaching out, and great to hear you're interested in the planning aspect of CALDERA.

First, I'd note that the LAVA simulation environment was ultimately never released publicly: the environment was _very_ proof of concept, and never quite was ready to be released for public consumption or maintained in the long term. Under some scenarios the code _can_ be made available, but we'd have to go through MITRE's technology transfer office to discuss licensing terms. If you do want to pull that thread, feel free to send an email over to caldera@mitre.org.

Regarding the planning algorithms themselves, we ultimately developed three different planners, summarized as such:

- The full planner, which was introduced in our "Intelligent,..." paper and tried to guess as to what the world looked like for planning.
- The lite planner, which was introduced in our "Analysis of..." paper and only tried to guess as to what the immediate world looked like for planning.
- The heuristic-best guess planner, which was discussed in our "Automated..." paper and planned by assuming best-case outcome.

Implementation-wise, the full planner and lite planner were only implemented in LAVA and never realized in the actual CALDERA code -- implementing these proved much too difficult.

The heuristic-best guess planner was implemented, but in an older version of CALDERA: in April 2019 we released CALDERA "v2.0", which separated operations into "adversary mode" and "chain mode". Adversary mode was all of the old CALDERA capability, where CALDERA used the heuristic planner and featured the logical language discussed in "Automated...". Chain mode was brand new, and was geared more towards a planner-less operation that orchestrated more atomic-style unit tests. Over time we ended up dropping adversary mode as it was overly complex and harder to extend/run/install, instead modifying chain mode to give it more fully-fledged features.

Today, CALDERA has moved away from the old semi-rigid logic that was in adversary mode, and now uses a more simple/intuitive scheme where we have facts, variables, parsers, and relationships. This has made it easier to write basic planners to extend CALDERA, as well as to add new abilities to the software -- whereas the old adversary mode topped out at ~35 abilities, our current version of CALDERA features ~500 out of the box. By default we only include some relatively basic planners, as our hope is that the community can use the new infrastructure to better write their own planners as they see fit. We do have plans to reimplement + release an updated version of the heuristic best-guess planner, but this is admittedly lower priority on our roadmap.

Hopefully this helps. For some more information:

- How CALDERA currently uses facts/edges: https://caldera.readthedocs.io/en/latest/How-CALDERA-makes-decisions.html
- How CALDERA currently does planning: https://caldera.readthedocs.io/en/latest/How-to-Build-Planners.html
- A short description regarding the shift from v1.0 to v2.0: https://caldera.readthedocs.io/en/latest/CALDERA-2.0.html
- The adversary plugin for v2.0 (**Note:** if I'm remembering correctly this plugin will only work with CALDERA v2.3.*): https://github.com/mitre/adversary
- The adversary mode planner implementation: https://github.com/mitre/adversary/blob/master/app/logic/planner.py
- The specific function used to evaluate plans in adversary mode: https://github.com/mitre/adversary/blob/master/app/logic/planner.py#L642

**Comment by jcleary47** [comment]
> 
> 
> Hey! Thanks for reaching out, and great to hear you're interested in the planning aspect of CALDERA.
> 
> First, I'd note that the LAVA simulation environment was ultimately never released publicly: the environment was _very_ proof of concept, and never quite was ready to be released for public consumption or maintained in the long term. Under some scenarios the code _can_ be made available, but we'd have to go through MITRE's technology transfer office to discuss licensing terms. If you do want to pull that thread, feel free to send an email over to [caldera@mitre.org](mailto:caldera@mitre.org).
> 
> Regarding the planning algorithms themselves, we ultimately developed three different planners, summarized as such:
> 
>     * The full planner, which was introduced in our "Intelligent,..." paper and tried to guess as to what the world looked like for planning.
> 
>     * The lite planner, which was introduced in our "Analysis of..." paper and only tried to guess as to what the immediate world looked like for planning.
> 
>     * The heuristic-best guess planner, which was discussed in our "Automated..." paper and planned by assuming best-case outcome.
> 
> 
> Implementation-wise, the full planner and lite planner were only implemented in LAVA and never realized in the actual CALDERA code -- implementing these proved much too difficult.
> 
> The heuristic-best guess planner was implemented, but in an older version of CALDERA: in April 2019 we released CALDERA "v2.0", which separated operations into "adversary mode" and "chain mode". Adversary mode was all of the old CALDERA capability, where CALDERA used the heuristic planner and featured the logical language discussed in "Automated...". Chain mode was brand new, and was geared more towards a planner-less operation that orchestrated more atomic-style unit tests. Over time we ended up dropping adversary mode as it was overly complex and harder to extend/run/install, instead modifying chain mode to give it more fully-fledged features.
> 
> Today, CALDERA has moved away from the old semi-rigid logic that was in adversary mode, and now uses a more simple/intuitive scheme where we have facts, variables, parsers, and relationships. This has made it easier to write basic planners to extend CALDERA, as well as to add new abilities to the software -- whereas the old adversary mode topped out at ~35 abilities, our current version of CALDERA features ~500 out of the box. By default we only include some relatively basic planners, as our hope is that the community can use the new infrastructure to better write their own planners as they see fit. We do have plans to reimplement + release an updated version of the heuristic best-guess planner, but this is admittedly lower priority on our roadmap.
> 
> Hopefully this helps. For some more information:
> 
>     * How CALDERA currently uses facts/edges: https://caldera.readthedocs.io/en/latest/How-CALDERA-makes-decisions.html
> 
>     * How CALDERA currently does planning: https://caldera.readthedocs.io/en/latest/How-to-Build-Planners.html
> 
>     * A short description regarding the shift from v1.0 to v2.0: https://caldera.readthedocs.io/en/latest/CALDERA-2.0.html
> 
>     * The adversary plugin for v2.0 (**Note:** if I'm remembering correctly this plugin will only work with CALDERA v2.3.*): https://github.com/mitre/adversary
> 
>     * The adversary mode planner implementation: https://github.com/mitre/adversary/blob/master/app/logic/planner.py
> 
>     * The specific function used to evaluate plans in adversary mode: https://github.com/mitre/adversary/blob/master/app/logic/planner.py#L642

Since we are on the subject, I had a question. If we were wanting to throw everything Caldera has to offer in terms of abilities at a lab machine just to establish a baseline for what does and doesn't work off the bat, and what we can and cannot detect, would there be a best practice for "planning" that?

It sounds like running in bucket mode might be best, since it sounds like it will run through everything once, gather the facts it can, and then try again after it has some (hopefully) discovered facts it can use. Is that correct?

Also, do you have any documentation as to what abilities will collect facts that are necessary for other abilities to successfully execute, or attempt to execute?

Thanks,

**Comment by wyc7** [comment]
Dear aapplebaum:
First of all, thank you very much for answering my question, and I am studying CALDERA further based on your suggestions.

I have read the full documentation of CALDERA(readthedocs) several times in detail. I have some understanding of the relationship between facts, variables, rules, and objectives (for example, variables can be filled with facts collected during operations to unlock the ability to own this variable; rules can allow or deny collected facts; When the collected facts meet the objective, the operation can be completed, etc.). However, I have a few questions.

- Except for the facts mentioned in the document (such as host.user.name, file.sensitive.extension, etc.), I don't understand the trait of facts, that is, how many descriptors are there to identify fact types?Besides host, user, name, file, etc., what other descriptors are there?Is there a complete descriptor document?
- There is very little content about the parser in the document("How CALDERA makes decisions"), so I can't understand the role and principle of the parser, and how does CALDERA use the parser to make decisions?

Thanks.

**Comment by aapplebaum** [comment]
@jcleary47 -- that's a good question. The bucket planner would indeed get you most of the way there -- as you say it'll run abilities that it currently can, gather new facts, and then run additional abilities as the new facts make them available, terminating the operation only when it's absolutely exhausted everything. I think this would get you most of the way there, but for baselining purposes I could see you wanting to add e.g. breakpoints to pause the operation before shifting to the next bucket. You'd also want to build out some scripts to perform sufficient analysis of the operation once it completes.

Unfortunately at this time we don't have good documentation to describe the interdependencies of abilities with regards to their facts/relationships/parsers. When we still had adversary mode integrated in CALDERA we had a prototype feature that helped here some [1], but current CALDERA's logic structure has been a moving target so we haven't re-incorporated that feature. With that said, we have noticed that it can be challenging building new adversary profiles as it's not always clear how the abilities relate during construction, and we do have plans to add features to make the process easier, potentially including a fact explorer/ability navigator. As a first step, we're currently in the process of re-architecting CALDERA's fact structure to better impose more standardized definitions, from which we'll have a better starting spot to build those more advanced features.

[1] -- Adversary mode had a feature where it would highlight abilities that couldn't be executed because the adversary profile didn't have the appropriate prerequisites for said abilities. This is likely something we'll look into re-integrating, as well as extending.

**Comment by aapplebaum** [comment]
@wyc7 -- CALDERA does not currently enforce a strict ontology/data schema, so the fact names + traits can be defined by the user as needed; i.e., if you add in your own abilities you're free to choose your own naming conventions for the facts + their traits. This is a really powerful feature for adding in new/custom abilities as you don't need to learn CALDERA's naming nuances to add in these abilities, but we've realized that this makes it challenging to add in new abilities _aligned with existing ones_ because we don't have such a schema [1]. That said, as I mentioned to jcleary47, we're hoping to release a re-architect of the data schema relatively soon, and this will include better naming conventions + the documentation that refers to them.

On your second point, the short version is that sandcat will execute an ability, read standard out after execution, and forward that text blob over to the CALDERA server. Once the server receives the blob, it looks up the ability and identifies specifically _which_ parser it should use, and then calls that parser to pull the relevant facts from the blob; once those facts are pulled, they're added to CALDERA's knowledge base and can be used in future abilities as input.

Parsers themselves are written in Python, and there's no restrictions on how they operate. By default, stockpile includes a variety of parsers here: https://github.com/mitre/stockpile/tree/master/app/parsers. Some I'd call out as examples:

- https://github.com/mitre/stockpile/blob/master/app/parsers/basic.py pulls each line from standard out
- https://github.com/mitre/stockpile/blob/master/app/parsers/katz.py is more complex and pulls usernames/passwords out of mimikatz output
- https://github.com/mitre/stockpile/blob/master/app/parsers/ipaddr.py is used to help identify IP addresses

Unfortunately we don't have documentation yet on how to build new parsers, but some of the ones in stockpile should help as examples.

[1] -- An example challenge here is we'll have some abilities that need as input a remote host's IP address, but these abilities can use a variety of variables to represent it, such as remote.host.ip, host.ip.address, target.host.ip, etc. The re-architecture should help standardize these.

**Comment by aapplebaum** [comment]
I'm going to close this issue for now -- feel free to reopen for anything pressing. We also have [discussions](https://github.com/mitre/caldera/discussions) open for more open-ended discussion.
