### ISSUE TITLE
Service Creation Lateral Movement

### ISSUE THREAD

**Issue by Difficultcl** [mitre/caldera#2162]
Hello, I have a problem recently. After running Service Creation Lateral Movement, the third ability failed.
![image](https://user-images.githubusercontent.com/38584419/119255261-5d2ff780-bbed-11eb-8e6b-07b414863f36.png)
![image](https://user-images.githubusercontent.com/38584419/119255319-b7c95380-bbed-11eb-94a6-a072ef1b4a2b.png)
Get-Process : Couldn't connect to remote machine.

After that, I run the powshell locally and start the service remotely.
![image](https://user-images.githubusercontent.com/38584419/119255368-ff4fdf80-bbed-11eb-986b-f05c99eee20c.png)

Finally, I found the 'sandsvc' service on the target machine, but I couldn't start it.
![image](https://user-images.githubusercontent.com/38584419/119255478-a5034e80-bbee-11eb-9787-9a728f6f7735.png)
![image](https://user-images.githubusercontent.com/38584419/119255598-3f639200-bbef-11eb-85bf-515f3b13b57f.png)
![image](https://user-images.githubusercontent.com/38584419/119255605-48546380-bbef-11eb-9bfd-a6f415f3df73.png)

I've looked for a lot of ways to solve this problem, but the problem still exists. Can you help me?

**Comment by Difficultcl** [comment]
Today, I tried to run the service startup statement manually, and found that if the originLinkID parameter was used, the command did not respond, but after deleting the originLinkID parameter, the command ran successfully and the agent was generated.

with originLinkID
![image](https://user-images.githubusercontent.com/38584419/119346564-f550de00-bccc-11eb-8817-fb8dd56fe26a.png)

without originLinkID
![image](https://user-images.githubusercontent.com/38584419/119346744-321cd500-bccd-11eb-8587-47548143f234.png)
![image](https://user-images.githubusercontent.com/38584419/119346701-24674f80-bccd-11eb-9770-700110b800f8.png)
![image](https://user-images.githubusercontent.com/38584419/119346450-caff2080-bccc-11eb-9e90-a243494d9804.png)

**Comment by wyc7** [comment]
Hi @blackwidow0616 ，we still haven't solved this problem. 
Supplement: We use Window Server 2008 R2 as the domain controller, and two Win10 machines join this domain. One of them logged in with the domain controller's account and password, and generated an agent with “Elevated” privilege on this one. The other one serves as the target host for lateral movement and logs in as a domain user.

**Comment by blackwidow0616** [comment]
I am still looking into this to get a more concrete answer, but if I'm understanding everything correctly the originLinkID parameter is what's causing the problem, which is optional. The originLinkID is used to see the attack path in the Debrief plugin. So you can remove that parameter from the command within the ability by editing the ability from the adversary tab. However, as I'm not sure why this is causing problems I will continue looking into this issue.

**Comment by Difficultcl** [comment]
Thank you for your reply, I remove that parameter from the command within the ability by editing the ability from the adversary tab, but the ability still failed. Curiously, the new agent is generated.
![image](https://user-images.githubusercontent.com/38584419/120766355-bcc2c700-c54c-11eb-8649-dfbaaf15ce9b.png)
![image](https://user-images.githubusercontent.com/38584419/120766354-bcc2c700-c54c-11eb-8ca0-49371e21fee4.png)

**Comment by wyc7** [comment]
Hi @blackwidow0616 ，We removed the originLinkID parameter. Although the "Service Creation" ability showed a failure, the s4ndc4t agent was turned on and connected back to Caldera. But we found a new problem:
The s4ndc4t agent generated on the WYC2 host by lateral movement will use the FQDN fact of WYC2 to continue to run the "View remote shares" and "Service Creation" abilities on the WYC2 host, and generate a new s4ndc4t process. Then the latest s4ndc4t agent will continue to repeat the above steps, forming an infinite loop. This is obviously illogical. How to solve this problem?

Screenshots：
1.Infinite loop operation, paused:
![image](https://user-images.githubusercontent.com/48666541/121043924-a84e2b00-c7e7-11eb-8b96-3345b857fe19.png)
2.Multiple agents are returned from the WYC2 host, which is completely unnecessary:
![image](https://user-images.githubusercontent.com/48666541/121044425-1bf03800-c7e8-11eb-854e-e37c6eae8bc6.png)
3.Multiple s4ndc4t processes are created on the WYC2 host, redundant:
![image](https://user-images.githubusercontent.com/48666541/121046006-79848480-c7e8-11eb-94a9-44b522a3aa2e.png)

**Comment by uruwhy** [comment]
Regarding the originLinkID parameter - we had made some recent changes to the link ID format (switched from int to UUID string), but those updates hadn't followed through to the full agent code. Long story short, the agent binary expects the argument to be an int rather than a UUID string, so the original service creation ability fails to run the executable. The ability will still run fine without the `originLinkID` argument. However, the inconsistent ID format is a bug that will need to be addressed.

Regarding the ability failure status with successful new agent beacon - it looks like the ability status shows as failure because the last command of the ability (`Get-Process ....`) fails (due to failed connection, etc). You may very well still have a new agent beacon successfully created. Normally, the `Get-Process` cmdlet will indicate lateral movement success, since it's looking for the new sandcat process on the remote machine. However, in your case there was some sort of connectivity issue that made caldera think that the ability failed overall, since `Get-Process` didn't work.

Regarding the infinite lateral movement loop - the lateral movement ability is currently set to be a singleton ability, meaning the operation shouldn't run the same command again if it succeeds. However, since the service creation abilities are "failing" due to `Get-Process` being unable to connect to the remote host, the operation thinks that the previous lateral movement attempts have failed, and will thus continue more attempts. We can take the currently existing agent beacons into account using the "no backwards movement" requirement, which will basically check to see if the `remote.host.fqdn` fact value references a host that already has an agent running on it that is part of the operation. If the host already has an agent running, then the operation will not try to laterally move to it.

**Comment by wyc7** [comment]
Hi @uruwhy , I combined your explanation, and then removed the Get-Process cmdlet from the command of the  "Service Creation" ability. Now the ability status is shown as successful, and the infinite lateral movement loop is resolved，but I know this is only a temporary and Low-level solution.
Recently, I am not satisfied with using the atomic planner to run the adversary profiles of "Service Creation Lateral Movement", but want to build my own planner, but I ran into a problem.
I wrote a simple planner in accordance with the "How to Build  Planners" document. However, after experimenting many times, I found that the abilities under the lateral movement tactic will not be executed by the lateral movement bucket(The same goes for Windows Worm in adversary profiles). I don't know where the problem occurred.
Screenshots：
![image](https://user-images.githubusercontent.com/48666541/123603535-8d8e3580-d82c-11eb-82bf-b7ad2d39340f.png)
![image](https://user-images.githubusercontent.com/48666541/123603597-9e3eab80-d82c-11eb-89ae-107308cdea3a.png)
![image](https://user-images.githubusercontent.com/48666541/123603633-aac30400-d82c-11eb-88a4-bbc305254e94.png)
Can you help me? Thanks in advance!

**Comment by uruwhy** [comment]
Hi @wyc7 . If possible, would you mind opening a new question regarding the planner? That way, we can keep this thread just for issues with the adversary profile/abilities.

**Comment by blackwidow0616** [comment]
Hopefully this resolves your issue regarding Service Creation Lateral Movement. If you’re still having any problems, please feel free to re-open or start a new ticket. Thanks!
