### ISSUE TITLE
The problem of agent privilege escalation

### ISSUE THREAD

**Issue by wyc7** [mitre/caldera#2170]
Hi, I have a question. 

If I have generated an agent with "User" privilege, do I run some abilities (for example: abilities under privilege-escalation tactics) on this agent to elevate the agent's privilege to "Elevated"?

**Comment by blackwidow0616** [comment]
I am looking into this, and I will get back to you as soon as I have more information.

**Comment by uruwhy** [comment]
Good morning - we do not currently support an agent being able to switch itself from "User" to "Elevated". However, the agent can run privilege escalation commands/abilities to spawn a new elevated beacon. So the end result will be 2 agent beacons (one "User" and one "Elevated"), rather than a single agent beacon switching from User to Elevated. Feel free to use currently existing privilege escalation abilities or try out your own techniques (e.g. UAC bypass, exploiting vulnerabilities, etc)

**Comment by wyc7** [comment]
I see, thank you！
