### ISSUE TITLE
The lateral movement bucket method in the created planner does not perform the lateral movement ability

### ISSUE THREAD

**Issue by wyc7** [mitre/caldera#2189]
Hello, CALDERA team. Recently, I am not satisfied with using the atomic planner to run the adversary profiles of "Service Creation Lateral Movement", but want to build my own planner, but I ran into a problem.

I wrote a simple planner in accordance with the "How to Build Planners" document. However, after experimenting many times, I found that the abilities under the lateral movement tactic will not be executed by the lateral movement bucket(The same goes for Windows Worm #1,2,3 in adversary profiles). I don't know where the problem occurred.

Screenshots：
![image](https://user-images.githubusercontent.com/48666541/123732514-99313900-d8cc-11eb-8d16-b22a1846fc6e.png)
![image](https://user-images.githubusercontent.com/48666541/123732598-b534da80-d8cc-11eb-89bf-5bc43ef2d04f.png)
![image](https://user-images.githubusercontent.com/48666541/123732645-c7167d80-d8cc-11eb-817e-813dd882f3eb.png)
![image](https://user-images.githubusercontent.com/48666541/123732673-d3023f80-d8cc-11eb-89cc-6ac144ff88f1.png)

Can you help me? Thanks in advance!

**Comment by mrengstrom** [comment]
@wyc7 You may want to try changing to `lateral-movement` for the bucket name string, as that is the format used in most of stockpile for the tactics and may be where you are having an issue.

the buckets for abilities to use in the `exhaust_bucket` call are either explicit buckets specified in the ability yml files or the tactic on the ability
https://github.com/mitre/caldera/blob/master/app/service/data_svc.py#L160

the buckets in `self.next_bucket`, is really the next state from within the state machine which would match the method names in the created planner.  So there is that small differentiation to make and to catch to avoid issues.

**Comment by wyc7** [comment]
Hi @mrengstrom , if I want to get information about the agent (including those generated at the beginning and generated by lateral movement) in this planner, such as id (paw), host, contact, pid, privilege, etc. What should I do?

**Comment by uruwhy** [comment]
You can get the current agents active in the associated operation by calling `await self.operation.active_agents()` or `self.operation.agents` from the planner. Note that you'll have to keep track of which agents existed when the operation started so that you can determine which new agents pop up due to lateral movement, priv esc, etc. You can iterate over these agents - each one references an agent object within CALDERA.

For the agent properties:
- paw: `agent.paw` (string)
- host: `agent.host` (string)
- contact name: `agent.contact` (string)
- pid: `agent.pid` (int)
- privilege: `agent.privilege` (string)

For further documentation, see https://caldera.readthedocs.io/en/latest/_generated/app.objects.html?highlight=c_agent.py#app.objects.c_agent.Agent. The agent Python file can be found in `app/objects/c_agent.py`.

**Comment by wyc7** [comment]
Hi @uruwhy, I have used **self.operation.agents[i].paw** and **self.operation.agents[i].host** to obtain the attributes of the currently active agents. However, I want to obtain the fully qualified domain name (**fqdn**) of the agent's host, but I found that the agent does not have an fqdn property, that is, **self.operation.agents[i].fqdn** is wrong. What should I do to get **fqdn** instead of **host**?
In addition, I want to obtain the status result of each ability after execution in the planner: success or failure. I am currently calling **self.operation.ran_ability_id(self.operation.adversary.atomic_ordering[i])**. If the return value is true, it means that the i-th ability is successfully executed, otherwise, the ability fails to execute. Is my solution correct?

**Comment by uruwhy** [comment]
Regarding the FQDN, the `host` property for the agent only provides the hostname rather than the entire FQDN (currently, the hostname is fetched via the `os.Hostname()` golang method. If you need the entire FQDN without changing the agent golang source code, you would have to create an ability that finds and saves the FQDN as a fact.

`self.operation.ran_ability_id` only shows if that ability was run and finished executing - it doesn't tell you if it was successful or not. Keep in mind that a single ability can be run more than once in an operation, for instance if your ability references a fact that has multiple values. In other words, you can have multiple "links" for an ability (links represent single components of an operation command chain). So if you want to look at a successful/failed step in an operation, you want to reference the link status. An example check to see if the link was successful: `if link.status == link.states.get('SUCCESS'):`.

The different link states are as follows (you can reference these by calling `link.states.get(STATE_NAME)`:
- SUCCESS
- ERROR
- TIMEOUT
- PAUSE
- DISCARD
- EXECUTE
- UNTRUSTED
- HIGH_VIZ

If you need more reference, you can look at the link source code in `app/objects/secondclass/c_link.py`

**Comment by wyc7** [comment]
Regarding the link object, I thought about it before and tried to use it, but there was a problem: self.operation didn't have a link object, so I couldn't refer to it in the planner. And I have been thinking about it for a long time, but I can't figure out how to get the link objects executed by each ability in the planner in the order of ability execution.

![image](https://user-images.githubusercontent.com/48666541/124634674-2ff78a00-deb9-11eb-88dd-7210ffbc832d.png)
As shown in the figure above, how can I use the link object in the planner to obtain the link of each ability in the order of ability execution?

**Comment by uruwhy** [comment]
So in the operation object, you have the `chain` variable, which is essentially a list of Link objects. They should be in the order of execution, and you can reference the chain from the planner via `self.operation.chain`
