### ISSUE TITLE
Check agent status programmatically

### ISSUE THREAD

**Issue by Anihilakos** [mitre/caldera#2193]
Hello,
I am interested in programmatically deploying, instructing and monitoring (e.g., status) of the agents. I have managed to do the deployment via the generated commands and the instruction via the REST API but I can't seem to find a way to probe an agent and check its status, e.g., what was the last ability it executed successfully? what was the output of the ability and so on.
The only way I can think of right now is monitoring the stdout of an agent; but considering that caldera already utilizes this information via the GUI, I am wondering if I am missing something.
Thanks in advance,
I.

**Comment by Anihilakos** [comment]
Hello,
I don't think this is mentioned somewhere in the docs.
BR,
I.

**Comment by uruwhy** [comment]
Hello,

If you're interested in querying output from an operation, we are currently in the process of implementing a new version of our REST API. Once the API endpoint for operations is completed, you'll be able to query an operation by ID to find all the links (commands run) within the operation. From there, you would be able to process the output to filter out links assigned to a particular agent, etc. We do have a new version of the API endpoint for agents, but the agent output there only seems to show commands that were assigned outside of operations (e.g. bootstrap abilities). So you wouldn't really get "all" the commands run by an agent, since an agent can also run commands in the context of an operation.

**Comment by Anihilakos** [comment]
Hello,
thanks for getting back to me.  That sounds perfect for the operations and will definitely use it, but actually I could use the existing API that you mentioned, because right now I am using the access plugin (/plugin/access/exploit) to execute commands outside the scope of operation (and would like to try bootstrap abilities too), so being able to know when the command was received and executed by the agent is very useful.  
BR,
I.

**Comment by uruwhy** [comment]
Great! If those commands are not showing up in the agent API results, let me know and I can take a look at how we handle them in the access plugin.

**Comment by Anihilakos** [comment]
Can you please point me on the endpoint that you are referring to (the completed one)? because I am checking the https://caldera.readthedocs.io/en/latest/The-REST-API.html and can only see two endpoints related to agents. I also checked (master) app/api/rest_api.py  but I didn't see anything related. I did check on some different branches too just in case, but no luck. Thanks.

**Comment by uruwhy** [comment]
Version 2 of the agents endpoint can be found by querying `/api/v2/agents` and `/api/v2/agents/{paw}`

`GET /api/v2/agents` - fetch information for all agents
`GET /api/v2/agents/{paw}` - fetch information for agent specified by `{paw}`

**Comment by Anihilakos** [comment]
That's perfect thanks!

**Comment by uruwhy** [comment]
You're very welcome! Please let us know if you have any other questions.
