### ISSUE TITLE
How to host & download payloads from server itself

### ISSUE THREAD

**Issue by zorovj** [mitre/caldera#2235]
Hello,

As my target client does not have an internet connection I want to host the payloads on the server itself and download it from there to the client machine. Is there a way to do it from the GUI? I have a Docker container running as server and an active sandcat agent deployed and want to use various abilities with payloads. I checked the documentation part for it but did not understand it well. Kindly please tell me how to do it with an example. 

Thanks!

**Comment by ArtificialErmine** [comment]
Hey @zorovj - Thanks for reaching out. Let me see if I understand your request correctly: You want to host payloads on the Caldera server so that agents can download them as part of abilities and run them locally, without needing to reach out to the internet? This should already be possible (and occurring by default in the base installation), and I can walk you through the process of creating a new ability that references a payload stored within Caldera if that is indeed what you are after, but if I have misunderstood, please correct me.

Unfortunately, the method I'm describing does not really work through the GUI, and would require accessing the docker container's file structure, at which point the changes would be possible with a few edits to some yaml files. 

Hopefully this is heading in the right direction - if so, let me know, and I'll get you more specific steps describing how to accomplish your goals.

**Comment by ArtificialErmine** [comment]
Given the lack of activity, I'm going to close this ticket. If the problem persists, feel free to re-open it or file a new one.
