### ISSUE TITLE
Problem in starting the Manx Agent

### ISSUE THREAD

**Issue by BIGdeadLock** [mitre/caldera#2240]
I tried running the Manx agent in one of my machines but I get the following error:

![image](https://user-images.githubusercontent.com/64005996/130972568-20391788-6b4d-407b-a895-b6f7426fe6c0.png)

The manx.go file is located in the local dir and have the executable privileges as you can see here:

![image](https://user-images.githubusercontent.com/64005996/130972992-8d85df16-7c6b-4639-a7f0-109f03b37abc.png)
 

**To Reproduce**
1. Try starting the agent using the command:
server="http://0.0.0.0:8888";socket="0.0.0.0:7010";contact="tcp";curl -s -X POST -H "file:manx.go" -H "platform:darwin" $server/file/download > manx.go;chmod +x manx.go;./manx.go -http $server -socket $socket -contact $contact -v

(I'm using a different ip than the localhost)

**Desktop **
 - OS:  Ubuntu 18.04
 - Browser chrome
 - Version 3.1.0

**Comment by uruwhy** [comment]
@BIGdeadLock From your screenshot, it looks like your manx.go file is only 14 bytes. This is most likely because the download failed due to a connection or compilation error, and so the error message was saved to the file rather than the actual compiled binary . If you cat the file, you should be able to fetch the error message. 

Could you verify that you have golang installed on the machine running CALDERA? If you also look at your server output, you can see if there were any compilation issues when requesting the manx.go file.

**Comment by wbooth** [comment]
Hopefully this issue has been resolved -- if not please feel free to re-open or create a new issue, thanks !
