### ISSUE TITLE
Caldera latest version: Unable to Create agent for contact points

### ISSUE THREAD

**Issue by ChiefK6** [mitre/caldera#2357]
After following the steps provided I am unable to create an agent for contact points. after doing all of it correct the agent doesn't show up. I put the code into PowerShell and it went through but doesn't show up in the agent tab

**Comment by ChiefK6** [comment]
Did I explain that okay to fix the problem or is more detail needed?

**Comment by cyber-arsenull** [comment]
@ChiefK6 
A few questions:

- Is this issue still persisting with the master branch of CALDERA?
- Does powershell give you any issues or errors? 
- What OS version is this on? 
- Does windows defender or any other software pop up or alert during this process?
- Do you see the file created in `C:\Users\Public`?
- Do you see any reporting on the server in the run log (try using `--log debug` when running the server)

**Comment by ChiefK6** [comment]
- Tested with latest master branch installed today (11/30)
- Yes the issue is still persisting.
- No, the power shell code goes through and looks as if nothing happened.
(No error message)
- Caldera server is installed on Ubuntu 18
- Windows version is Server 2016

I tested it again today and the solution guide took me through and an agent
came out of it. The problem is when the training is “complete” it doesn’t
highlight the “contact points” in red like it’s supposed to.

**Comment by cyber-arsenull** [comment]
Hey @ChiefK6 sorry for the late response. 

To make sure I am on the same page, you say 
> I tested it again today and the solution guide took me through and an agent
came out of it.  The problem is when the training is “complete” it doesn’t
highlight the “contact points” in red like it’s supposed to.

Does that mean the only issue right now is the training module is not marking "complete" correctly? If so, what challenge are you currently on? I think others have had a similar issue. Due to the transition to the new GUI the training has some issues showing up. 

If you have a screenshot for anything specific that you are seeing, such as the "contact points" not being highlighted, that may help as well.

**Comment by ChiefK6** [comment]
[image: 2021-11-12 14_50_02-Window.png]
yes. everytime i complete the steps it doesn't highlight contact points and
allow me to move forward onto the next module

**Comment by cyber-arsenull** [comment]
Ok, that tracks then. Your image didn't seem to load unfortunately. 
I'm assuming it is test 6 "Contact Points" with description "Deploy a new agent, using a different contact point then your first agent"?
This one had you deploy a manx agent. With version 4.0 there is currently an issue with manx integration. Tomorrow I will get you a solution to bypass this challenge, let me just ask the team what they think is the best way we want to resolve it.

**Comment by ChiefK6** [comment]
I do believe so!
Thank you so much for your time and help!

**Comment by cyber-arsenull** [comment]
Hey @ChiefK6 I decided to test the trainer module on the most recent master branch. Tested server on both Ubuntu 20 VM and Windows 10 host. Tested _manx_ agent on both as well. 
Below is my agent config for manx on Windows. Can you test a clean master pull with these settings?
![image](https://user-images.githubusercontent.com/4370241/146624811-2315637c-8ef2-4cb9-92ca-878978312acb.png)

I noticed you are testing on Windows Server 2016, and I will try that as well once my DetectionLab VMs are up.

**Comment by cyber-arsenull** [comment]
Hey @ChiefK6 I tested the most recent master with server on both Ubuntu 20 and Windows 10, and agents on Ubuntu 20 and Windows 10 as well. 
I believe the issue is that you need to have 2 active contact points at once time for the challenge to pass. So, so you will need to have both a `sandcat` and a `manx` agent running at once. 

Keep in mind that there is currently a bug with killing the `manx` agent from the GUI, so you will need to do the kill challenge on the `sandcat` one. 

Let me know if this solves the issue!

**Comment by onemillione** [comment]
Hello , i am face that the firewall of the windows detect the agent as virus so i can't install the agent .
should i turn off the firewall ?

**Comment by 3ls3if** [comment]
Yes
