### ISSUE TITLE
Wrong documentation for API:  GET ​/api​/v2​/abilities

### ISSUE THREAD

**Issue by Thorsten-Sick** [mitre/caldera#2441]
**Describe the bug**
The Swagger documentation is not up to date. The GET call to /api/v2/abilities for 4.0.0-alpha.2 returns additional items, not covered by the documentation:

* "custom_parser_vals" in the "parserconfigs"
* "relationships" in the "parsers" of the "executors"

HTH
Thorsten

**Comment by emmanvg** [comment]
Hi @Thorsten-Sick, thanks for reporting this. I can confirm that `api/v2/abilities`  under 4.0.0-alpha2 returns an item not covered under the documentation:

- "relationships" in the "parsers" of the "executors"

The other key you mentioned "custom_parser_vals" is expected in that location because according to the model this is a [ParserConfig ](https://github.com/mitre/caldera/blob/4.0.0-alpha.2/app/objects/secondclass/c_parserconfig.py#L36) object.

**Comment by Thorsten-Sick** [comment]
While implementing parts of the API I found other issues, should I post them here ? For example I am struggling with creating operations: 
Status code: 422
{'agents': {'name': ['Missing data for required field.']}}

Documentation justs asks for: 
POST /api/v2/operations 
Required nested schema fields are as follows: "adversary.adversary_id", "planner.planner_id", and "source.id".

**Comment by emmanvg** [comment]
@Thorsten-Sick sure, feel free to report other findings in this thread.

**Comment by elegantmoose** [comment]
Thank you @Thorsten-Sick.  Looking into now.
