### ISSUE TITLE
Plugin folder is not being cloned

### ISSUE THREAD

**Issue by thedunston** [mitre/caldera#2499]
**Describe the bug**

Hey folks, whenever I clone the repo or download the zip file from the GitHub repo, none of the contents of the plugin folders are cloned so I have to download the plugin folders and manually add them.

**To Reproduce**

Download a zip file from the Github page or clone the public repo.

**Expected behavior**

I expect to have the full contents of each folder cloned or within the zip file.

**Screenshots**

The attached screenshot is what I see in chrome for the plugins folder.

**Desktop (please complete the following information):**

The same behavior is seen on Windows when I open the plugin folders, each one is empty.

**Additional context**
![calderaPluginFolder](https://user-images.githubusercontent.com/43048165/154978704-aef2a8e6-b361-4f40-b23f-5c3dba627476.png)

**Comment by thedunston** [comment]
I didn't use the --recursive flag.  I just did and that worked.
 
 Since I was getting subdirectories for other files under other directories such as static/jquery/images,/*.png I didn't think that was the issue.  Why doesn't a standard clone w/o --recursive get the plugins directory, when it works on other directories, especially when those are required for caldera to start based on the default plugins being expected in the conf/local.yml file?

If those folders are not required, could the plugins be removed from the default conf/local.yml file, by default?

**Comment by argaudreau** [comment]
The plugins directory is different from the others because it only contains git submodules. The --recursive flag tells it to pull the commit it's pinned at so that it can populate the directory, otherwise it'll leave it bank. One of the reasons we go the submodule route is to be able to update the plugins independently from the main repo.

The default plugins are enabled because they're the most commonly used with CALDERA. If you prefer to run it without them, you can always remove the plugins from local.yml and add what you need later on.

**Comment by thedunston** [comment]
Okay.  Thank you!
