### ISSUE TITLE
Got an error when select a source

### ISSUE THREAD

**Issue by dickens88** [mitre/caldera#2510]
**Describe the bug**
Hi, I'm using 4.0.0-beta and i got an error after clicking a source name. after i click the fact source name, nothing shows below(It should show the details about facts and rule, etc). in addition, I also can't delete it bcos i can't see delete button.

I put the screenshot below. 

The problematic fact source was not made by myself, it was generated automatically when i run an operation.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8390209/156591626-68914632-46b6-4f27-b554-cb54a2198bdd.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [98.0.4758.102]

**Comment by argaudreau** [comment]
Hi @dickens88, this was fixed in #2501. We were seeing the behavior you saw when there were a large amount of facts, which is why `basic` and `Alice Filters` loaded fine. We will be working on this page in the future to improve its stability when loading and viewing a large source. 

If a fresh pull from master doesn't fix it please let us know.

**Comment by dickens88** [comment]
@argaudreau thank for the reply. I have pull the latest master code 4 days ago, so I think the issue was still there. Maybe the issue can be separated into two parts.
1. some auto-generated source facts can not display correctly.
2. after delete source facts from the web page, the yml files still keep in /data/sources. and if you restart the server, they will display on the web page again.
