### ISSUE TITLE
Adding the option of editing requirements/parses on the page.

### ISSUE THREAD

**Issue by dickens88** [mitre/caldera#2512]
**What problem are you trying to solve? Please describe.**
Hi, I'm using 4.0.0-beta. I found the `requirements` and `parses` options from [this docs](https://caldera.readthedocs.io/en/latest/How-CALDERA-makes-decisions.html). It's a very great function, but it seems it if I want to use it in my customized ability, the only way is to editing the yaml file of ability. I think it very inconvenient, you need to check several dirs for checking the names of `requirements` and `parses`. 

**The ideal solution: What should the feature should do?**
How about adding some options to the page that allow you to configure the `requirements` and `parses`.

**What category of feature is this?**

- [ ] UI/UX

**Comment by ArtificialErmine** [comment]
Hey @dickens88, thanks for bringing this to our attention! While we likely won't ever be able to fully support `requirements` and `parsers`  due to how creating new parsers requires writing python code, I'll look into the possibility of being able to leverage pre-existing options for these when creating and editing abilities.

**Comment by dickens88** [comment]
@ArtificialErmine Thank for the reply. That's a good idea, if you can support  pre-existing options operating on the web page that will make the operations much easier.

**Comment by ArtificialErmine** [comment]
We've added rudimentary support for this in #2525. Let us know what you think!
