### ISSUE TITLE
API updates to Abilities break them

### ISSUE THREAD

**Issue by ArtificialErmine** [mitre/caldera#2539]
**Describe the bug**
In an unfortunate turn of events, the approach to how the API handles updating on-disk abilities (and possibly other objects) creates a version of said object that cannot be successfully ingested by Caldera. In ability files, this is initially due to the creation of the `ability_id` field, which is not equivalent to the `id` field expected by older versions. The code in `app/service/data_svc.py` that handles this (`load_ability_file`) only checks for `id`, not `ability_id`, which then produces a bugged state that cascades, with a halt to loading any further objects that have not been ingested prior to this point.

**To Reproduce**
1. Launch the Server
2. Open up `abilities`, and modify, and then save the ability
3. Shut the server off
4.  Launch the Server again (potentially in `--fresh` mode)
5. Observe considerable missing abilities.

**Expected behavior**
Updates to objects through the API, both ability and otherwise, create updated yaml source files that can be read in at a future point in time.

**Desktop (please complete the following information):**
 - OS: Linux (AWS variant)
 - Browser: Firefox (behavior is independent of the UI)
 - Version: 4.0.0-rc2/master

**Additional context**
This problem was first noticed during https://github.com/mitre/caldera/pull/2532, but wasn't able to be fixed at the time. This will need to be addressed at some point before the API can really be used effectively, unfortunately. 
There are two possible paths towards solutions - 
1) Patch the API file saving approach to conform to existing stockpile file formats 
2) Update the ingest system to properly account for the new approach

**Comment by bleepbop** [comment]
Using the latest version of Caldera, I can't seem to recreate this issue. I tested with combinations of the following:
* creating an ability with the UI
* creating an ability directly with the API
* updating existing plugin and non-plugin abilities through both the UI and API
* creating yaml files directly, both in `/plugins` and general `/data`

I used `--fresh` to get an initial count of all plugin abilities. After modifying existing abilities (originating from both `/plugins` and the general `/data/abilities` folders) and rerunning with `--fresh`, the original amount of abilities remained, with the changes I had made appearing in the abilities originating from `/plugins`. Any abilities that were not in a plugin folder were removed (which should be the expected behavior when running with `--fresh`). I may close this for now unless another use case reveals the same issue. 

I believe the current API converts between `id` and `ability_id` keys - the former used in yaml files, with the latter exclusively being used in `ability` objects. This in theory should allow existing yaml files to be compatible with the API
