### ISSUE TITLE
Not having same behavior executing locally and with Caldera agent

### ISSUE THREAD

**Issue by Purpl3Lynx** [mitre/caldera#2578]
**Describe the bug**
Hello, everyone. I have this binary which I execute in my Windows VM locally and everything works fine. The problem is when I execute it through one of Caldera agents, either Manx or Sandcat. From the execution I would expect a lot of console output, but Caldera doesn't show any. If I monitor the execution with Procmon I see half the actions taken. It's like it executes but then it stops. Consequently, Caldera marks the operation as successful, but the process gets blocked somewhere I am unable to identify. I am running all this on a Windows machine with no AV or Defender active.

**To Reproduce**
1. Upload binary to Stockpile payloads folder
2. Create ability (Windows cmd and '.\my_binary', payload added)
3. Create adversary and add ability
4. Create operation, choose adversary and run.

**Expected behavior**
I expect this binary to write a file to memory then create a registry key, but I only see the first one when monitoring with Procmon. And I don't get any expected console output from Caldera when operation is finished. Operation is marked as successful because the binary executed, although not completely.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 100.0.4896.127

**Additional context**

**Comment by heatonk** [comment]
Hello!

I'm currently taking a look at this. One thing that comes to mind is if the agent is created and running with administrative permissions, as it sounds like that might be the issue.

Additionally, you can double check that the expected results in the [operation report](https://caldera.readthedocs.io/en/latest/Operation-Results.html) are what you would expect, or see where the issue arises.

**Comment by Urworstnghtmare** [comment]
Hi, thanks for your answer. Yes, the agent is created and running with admin privileges as they are needed to successfully run the binary. I do not get any hints on the issue by looking at the operation report so I am going to try debugging the running process.

**Comment by CDJellen** [comment]
Hello @Purpl3Lynx, in order to further debug the issue, it may be helpful to pipe stdout and stderr to a text file and compare the results of running manually through `cmd` or through caldera.  In the first instance, this can be accomplished by running:
```cmd
.\my_binary > out.txt
```
In the ability command, you can make the above change as well, piping to `out.txt` and than manually comparing the two files.  If the `out.txt` from the agent's execution shows different output than that of the `out.txt` generated by manually executing, please feel free to attach both and reopen this issue.

If the outputs look correct in the agent's `out.txt`, but stdout is not appearing in the caldera Operation tab, you can add the `/SUBSYSTEM:CONSOLE` argument to the ability's command, in order to force Windows to generate console output.  The root cause for Windows output not being reflected in caldera is often that executables are run with `/SUBSYSTEM:WINDOWS`, which does not records stderr and stdout in console.  Alternatively, you can rebuild the binary and specify `WinMain` as the entry point to change the default subsystem type for Windows.

Please let me know if the above helps, and thank you for posting the issue.
