### ISSUE TITLE
v4 adversaries not run in sequence

### ISSUE THREAD

**Issue by mhatib** [mitre/caldera#2593]
**Describe the bug**
On v4.0 beta, some adversaries do not run in sequence as determined in the adversary profile.

**To Reproduce**
1. Create an operation with the Thief profile
2. Start operation and observe "Create staging directory" executed
3. Operation then skips to "Compress staged directory" and skips both "Find files" & "Stage sensitive files" TTPs
4. Operation fails there

**Expected behavior**
The operation should be executed in sequence, as it does in Caldera v3.

**Screenshots**
Expected result (v3):
![image](https://user-images.githubusercontent.com/6824725/170665728-43c4f461-ad4f-4ac2-a00b-02dd3a4b8193.png)

Current result (v4):
![image](https://user-images.githubusercontent.com/6824725/170667520-b16f95bc-c3df-4b5a-a5a1-baa9a63a1f71.png)

**Desktop (please complete the following information):**
 - OS: Kali
 - Browser: Firefox
 - Version: 91.5esr

**Additional context**
Tested agents on both Linux and Windows systems. v4 compressing seems to fail because there are not files in the staged folder.

**Comment by CDJellen** [comment]
Hello @mhatib, the "fact source" in the Operation Report defaults to `Alice Filters` in `4.0.0 Beta`, but defaulted to `basic` in `3.1.0`.  In order to get the expected results, pictured in your first image, please select the `basic` fact source when starting an Operation with the Thief adversary.

The `basic` fact source has three entries for `file.sensitive.extension`, `.yml`, `.wav`, and `.png`.  In contrast, the `Alice Filters` source has none. The `file.sensitive.extension` fact is used to fill the "Find Files" ability executed by the Agent, so when using the `Alice Filters` fact source, the "Find Files" command cannot be filled from existing facts, and thus will not execute.  This results in the behavior pictured in your second image.

I've included some screenshots below which demonstrate the impact of the `basic` fact source in `3.1.0`.

**Version 3.1.0 Thief with `basic` fact source**

![image](https://user-images.githubusercontent.com/64814231/171031214-509772b1-f8e3-416f-883e-5283071a3566.png)

**Version 3.1.0 Thief with `Alice Filters` fact source**

![image](https://user-images.githubusercontent.com/64814231/171031311-8fc32c10-f2b8-4980-b54b-532e87db33b4.png)
