### ISSUE TITLE
Add feature to download debrief pdf report via API

### ISSUE THREAD

**Issue by L015H4CK** [mitre/caldera#2666]
**What problem are you trying to solve? Please describe.**
The API already offers many possibilities to interact with the CALDERA server.
Adding the possibility to download the PDF report created by the debrief plugin via API would be really useful to further automate CALDERA's functionalities.

**The ideal solution: What should the feature should do?**
The PDF report created by the debrief plugin should be downloadable via API.

**What category of feature is this?**

- [ ] UI/UX
- [x] API
- [ ] Other

**If you have code or pseudo-code please provide:**

Similar to the JSON report via curl:
```python
curl -X 'POST' 'http://localhost:8888/api/v2/operations/<operation-id>/pdfreport' -H 'accept: application/json' -H 'Content-Type: application/json' -H 'KEY: ADMIN123'
```

Alternatively:
```python
curl -X 'POST' 'http://localhost:8888/plugin/debrief/pdf' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"operations": ["<operation-id>"]}' -H 'KEY: ADMIN123'
```

**Additional context**
See discussion https://github.com/mitre/caldera/discussions/2658.

Note: In theory the pdf report (or more exact the pdf bytes) can already be downloaded via the API with a call like this:

```
curl -X 'POST' 'http://localhost:8888/plugin/debrief/pdf' -H 'accept: application/json' -H 'Content-Type: application/json' -H 'KEY: ADMIN123' -d '{"operations":["<operation-id>"], "graphs": {}, "header-logo": "", "report-sections": ["main-summary", "statistics", "agents"]}'
```

This results in a "basic report" that does not include the nice graphs created by the debrief plugin.
In order to get a report that includes the graphs, one would have to know the IDs/encoded values of the respective attackpaths, facts, steps, tactics and techniques - which I think is not realistic (see linked discussion update 2).

**Comment by argaudreau** [comment]
Thanks for the feature request, I agree that having the enriched report available via the API would be a nice to have. Currently, the graphs are rendered via D3 in the browser, which is why we can't simply add it as an API endpoint. The reports with the graphs that you can download via the API convert the graph to an SVG to save in the report, so we'd have to add some graphing library to the server-side of debrief to make that happen at the moment.

Debrief will be undergoing some upgrades to the graph in the future, so I've added this to our backlog so that we can address this once we dig into it.

**Comment by elegantmoose** [comment]
Closing as added to backlog. Thank you @L015H4CK
