### ISSUE TITLE
Caldera doesn't display Adversary profile in web interface

### ISSUE THREAD

**Issue by Aledangelo** [mitre/caldera#2667]
In the 'adversary' page, selecting a profile from the drop-down menu, the page freezes and that profile is not shown.

I would expect to see the characteristics of the selected profile.

**Comment by argaudreau** [comment]
Hi @Aledangelo, apologies for the delay in response. This can happen if there's an old version of Caldera or it's dependencies cached in the browser. Could you try hot-reloading the page?
`Ctrl + Shift + r` on Windows, `Cmd + Shift + r` on Mac for Firefox or Chrome. Otherwise, try and clear your cache and try again.

**Comment by Aledangelo** [comment]
I already tried this, but it didn't work. I uninstalled and reinstalled the latest version of Caldera, and I solved the problem. Now everything works fine except the fieldmanual plugin. I have already opened another issue for this.
