### ISSUE TITLE
T1083 Missing Requirement Rectification

### ISSUE THREAD

**Issue by FawwazAhamed** [mitre/caldera#2675]
Img 1: (https://user-images.githubusercontent.com/69192146/196657356-5a8fad07-0422-4c26-8182-ddae68c2c800.jpg)
Img 2: (https://user-images.githubusercontent.com/69192146/196657459-7e94fe56-91a7-4419-b843-751ccb5b9c04.jpg)

Hi,

The ability no. 2 (ref Img 1) is showing me a warning, when I expand on it, it says that I am missing out on a requirement (the lock). I am unsure of what I am supposed to do to rectify it.

Img 2 - Inside the ability

Kindly please guide me on how to rectify the issue, would certainly appreciate it.

Thanks a lot!

**Comment by argaudreau** [comment]
Hi @FawwazAhamed, when hovering over the lock icon on the ability row that is highlighted, it will tell you what facts it requires in a comma delineated list. In order to get rid of the warning, you'll need to add an ability to the adversary before it that unlocks that fact requirement. You can tell which facts an ability unlocks by hovering over the key icon.

**Comment by FawwazAhamed** [comment]
Hi @argaudreau, Thank you for your kind reply.

Using your advice, I hovered over the requirement issue, and found the following message:

This ability has requirements (host.system.path)

I did my research on trying to find a way to fulfil this requirement, but am unable to find a solution.

Would you be able to guide me/give me a sample of what the fix/command looks like so that I could rectify and learn

Thanks a lot!
