### ISSUE TITLE
Updating custom abilities

### ISSUE THREAD

**Issue by kwoodilla** [mitre/caldera#2677]
**Describe the bug**
When updating a custom ability the ability does not stay consistent after restarting the server. The ability is updated in the UI for as long as the server stays up but never written to the data/abilities/* directory.

**To Reproduce**
1. Create ability
2. Ensure file is written to abilities directory
3. Update ability in the web UI
4. restart server and change does not persist

**Expected behavior**
When saving the ability it should be written to the file to be persistent across restarts

**Desktop (please complete the following information):**
 - OS: Server - Kali; Client - Windows 10
 - Browser: Chrome
 - Version: 4.1.0

**Additional Info
I have not checked any of the built in abilities to see if this behavior is the same on them as well.

**Comment by L015H4CK** [comment]
I just checked my installation and everything worked as expected. I tried a custom ability from a custom plugin as well as built-in abilities from the stockpile plugin.

Did you check if you named the ability, tactic etc correctly? For me, if the tactic defined in the abilitiy's yml does not match the name of the ability directory, it is not updated and saved correctly. Instead of updating the file in the custom plugins directory (caldera/plugins/<plugin>/data/abilities/<tactic>), a new ability in caldera/data/abilities/<tactic> is created. Maybe your issue is somehow similar?
