### ISSUE TITLE
How can I build a plugin?

### ISSUE THREAD

**Issue by Aledangelo** [mitre/caldera#2682]
I wrote a script to automate the work with Caldera. I have to make it a Plugin for it but I'm having some trouble, for example:
* How can I get data from HTML form to python code?
* How should I structure the code?
* What are 'data_svc', 'rest_svc', 'auth_svc' and the other used for?

**Comment by argaudreau** [comment]
Hi, take a look at the [skeleton plugin](https://github.com/mitre/skeleton) for a good starting point on building a plugin. It includes the HTML template with some example logic, same with the server side code located in the `app/` directory. I'd start at `hook.py` since that's what contains most of the logic to set the stage if you will. Don't forget to run the plugin init script before you modify skeleton.

**Comment by Aledangelo** [comment]
Thanks, it helps me. I had a bit of a struggle just to use the caldera API from the plugin code (for example, create an adversary profile or an operation). I noticed that this part is not very well documented and to understand how to do it I had to study the code of the project.
I would suggest adding a small part about this in the API documentation or plugin documentation.
