### ISSUE TITLE
Can not create new adversaries and import APT29 adversary

### ISSUE THREAD

**Issue by LeukocytesTT** [mitre/caldera#2733]
I have just installed CALDERA version 4.1.0 using Docker environment. I followed [this repo](https://github.com/mitre-attack/attack-arsenal/tree/master/adversary_emulation/APT29/CALDERA_DIY/evals#round-2-adversary) and config caldera to import APT29 adversary.
I am struggling with some obstacles, please help me overcome these. Thanks so muck!

- After starting CALDERA server, I successfully deployed an agent on Windows victim and see imported APT29 abilities as **Fig.1** and **Fig.2**
- But I can not create a new adversary when clicking CREATE button, nothing happened,  or importing APT29 adversaries - It threw errors as **Fig.3** And when I click in one profile in pre-defined list, there is no ability in this profile. However, when click to add adversary, it shows those abilities as **Fig.4** and **Fig.5**
- In the Operations option, when creating and starting an operation, in docker terminal, it threw the error as **Fig.6**
- **_This is a sample of pre-defined APT29 adversary_**
`id: 3af0e59b-0d2a-48cd-b934-c46d5d1621d6
name: ATT&CK Eval APT3 - 5.B-8.A
description: Access Token Manipulation, Discovery for Lateral Movement, Persistence, and Discovery for Collection
visible: 1
phases:
  1:
    - 03afada1-1714-408f-bde5-f528b91dc89d`
- **Figure 1**
![image](https://user-images.githubusercontent.com/32612962/223003985-ccd88c58-1497-4550-8a39-9a90b1cbdd69.png)
**Figure 2**
![image](https://user-images.githubusercontent.com/32612962/223004078-2feba9c4-4a6e-4e0c-bb51-dcfc08a869f0.png)

**Figure 3**
![image](https://user-images.githubusercontent.com/32612962/223004134-ca649fea-5ea5-4b6e-b31a-9cc110ee83c7.png)
**Figure 4*
![image](https://user-images.githubusercontent.com/32612962/223007524-05770431-08ac-481f-9b9f-231e313bc10c.png)
** Figure 5 **
![image](https://user-images.githubusercontent.com/32612962/223007585-3fcb1196-2e99-4d3d-bad5-2635b6de3f18.png)

**Figure 6**
![image](https://user-images.githubusercontent.com/32612962/223004680-3d29fe96-f287-4e4a-a53a-f0ca581aa59d.png)

**Comment by L015H4CK** [comment]
Hi, unfortunately I cannot help you with this problem. For me, importing the APT29 adversary worked using a non-docker environment. Since I have no experience using CALDERA with docker I cannot tell if the error comes from docker or not.
Actually, you should not have to import the APT29 adversary profiles manually but they should be loaded automatically to CALDERAs adversary profiles as long as they are in the plugin's respective data/adversaries directory and the plugin is enabled in the config/default.yml.

But, I have some information regarding the attack-arsenal/adversary-emulation-library and APT29 that might be interesting for you as well.

The attack-arsenal repo that you linked was moved to the [adversary emulation library](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/). You can find a note in the attack-arsenal repo as well (`This content has been ported to https://github.com/center-for-threat-informed-defense/adversary_emulation_library as of January 2021. This format was preserved in [/Archive](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/tree/master/apt29/Archive).` - see [here](https://github.com/mitre-attack/attack-arsenal/tree/master/adversary_emulation/APT29)). The content of the original repo was moved [here](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/tree/master/apt29/Archive).

Another but: If you then intent to use the new adversary emulation library with the emu-plugin instead of the old evals-plugin, you will probably find that the generated APT29 adversary profile is faulty. More information on that can be seen in my [pull request](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/pull/120). Using the APT29 adversary emulation plan I also did not get the operation to work as expected - but I am still investigating this and it should not be a problem for you right now since you have other problems to fix first as it seems.

**Comment by LeukocytesTT** [comment]
> Hi, unfortunately I cannot help you with this problem. For me, importing the APT29 adversary worked using a non-docker environment. Since I have no experience using CALDERA with docker I cannot tell if the error comes from docker or not. Actually, you should not have to import the APT29 adversary profiles manually but they should be loaded automatically to CALDERAs adversary profiles as long as they are in the plugin's respective data/adversaries directory and the plugin is enabled in the config/default.yml.
> 
> But, I have some information regarding the attack-arsenal/adversary-emulation-library and APT29 that might be interesting for you as well.
> 
> The attack-arsenal repo that you linked was moved to the [adversary emulation library](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/). You can find a note in the attack-arsenal repo as well (`This content has been ported to https://github.com/center-for-threat-informed-defense/adversary_emulation_library as of January 2021. This format was preserved in [/Archive](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/tree/master/apt29/Archive).` - see [here](https://github.com/mitre-attack/attack-arsenal/tree/master/adversary_emulation/APT29)). The content of the original repo was moved [here](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/tree/master/apt29/Archive).
> 
> Another but: If you then intent to use the new adversary emulation library with the emu-plugin instead of the old evals-plugin, you will probably find that the generated APT29 adversary profile is faulty. More information on that can be seen in my [pull request](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/pull/120). Using the APT29 adversary emulation plan I also did not get the operation to work as expected - but I am still investigating this and it should not be a problem for you right now since you have other problems to fix first as it seems.

Hello. I tried to run CALDERA with non-docker option and configured the evals plugin but It still did not import adversary profiles automatically. I also tried your modification of emulation plan by importing .yaml file. It threw an error as the Fig.3

**Comment by L015H4CK** [comment]
When using the new emulation plans you no longer need the evals plugin - instead you enable the emu plugin. It automatically generates adversary profiles, abilities, etc from the given YAML adversary emulation plan and puts them into plugins/emu/data/adversaries, plugins/emu/data/abilities, etc.

Some questions that might help finding the problem here:
- Does CALDERA work as expected when you disable the evals plugin? So, is every adversary profile loaded as expected and can you run operations with them?
- Does CALDERA correctly load adversary profiles from any other plugin?
- Also, are you using the tagged 4.1.0 version or the master branch? I did not have any problems with the tagged version in the past - but I do not have the time to try and recreate the issue at the moment.

**Comment by LeukocytesTT** [comment]
Thank you so much! I have just run successfully with emu plugin!
