### ISSUE TITLE
Blue Training: Malicious File on System

### ISSUE THREAD

**Issue by jasonlmaynard** [mitre/caldera#2739]
In the training module - blue team

autonomous
-- Malicious File on System
Write a file on the Windows machine under the C:\Users\Public directory. Get the SHA256 hash of this file, and write it to C:\Users\Public\malicious_files.txt. The autonomous defender should automatically find and delete the file.

![image](https://user-images.githubusercontent.com/45973544/226468186-f3929ead-2319-47d8-b592-ac052a6d40e4.png)

File is removed but flag is not granted and I cannot move on in the training.

**Comment by jasonlmaynard** [comment]
any thoughts?

**Comment by nonalphanumeric** [comment]
The same thing happened to me two times, with this flag and the Blue Manual flag for malicious file.

Looking at the verify method for this flag in the Training plugin, we can see that Caldera validate this flag if the file was found and is the file has been deleted.

To check wether the file was found, Caldera uses the following checks:

- If the operation ran the ability with id 'f9b3eff0-e11c-48de-9338-1578b351b14b' _Hunt for known suspicious files_
- If there is value in file.malicious.hash and host.malicious.file facts

To check wether the file was deleted, the flag checks for:

- If the operation ran the ability '5ec7ae3b-c909-41bb-9b6b-dadec409cd40' _Delete known suspicious files_

My suggestions:

- Look if the correct abilities ran. 
- Hunt for known suspicious files might not run because of requirements issues, most importantly, the issue could be with the facts source. (This one saved me for the Blue Manual malicious file by switching from Response Training facts source to response facts source).
- Looking at the code, verify should return True if at least one of the operation called Blue Autonomous validate the conditions but in my case, cleaning up all operations actually helped for this flag. Still I can't explain why.


If you're doing several attempts, mind that _Acquire known suspicious files_ ability removes the malicious_files.txt file. I deleted the line Remove-Item C:\Users\Public\malicious_files.txt; in the command section of this ability to make things less tedious.
