### ISSUE TITLE
Step schtasks - Task scheduled in the past

### ISSUE THREAD

**Issue by thibc4** [mitre/caldera#28]
Hello, thank you for this great project!

When an implant is copied from one workstation to another using pass the hash, the **schtasks** step is then run to start this new Rat. 

The problem is that the schtasks step schedules a task to start 1 day before the current date. 
So for example, when net_time will rightly detect that the current time and date is **20 March** 15:00 on every workstation, schtasks will schedule the Rat to start on **19 March** 15:03 (approximately) . 

Configuration:

- Environment with 1 DC (Windows Server 2016) and 2 Workstations (Windows 10), caldera installed on each of them

- CALDERA is installed in Ubuntu 16.04 LTS

- The starting victim is a workstation, and the Rat is started as a logon user.

**Comment by dm-mitre** [comment]
Internally net_time stores the computer time as the difference between the caldera server time and the detected time. It looks like the bug is here: https://github.com/mitre/caldera/blob/master/caldera/app/operation/operation_steps.py#L644 

It is only storing second and microseconds but should also be storing days. Can you confirm that the caldera server's clock is set one day behind the target computers clock?

**Comment by thibc4** [comment]
The caldera server's clock is set at the same time as the target computers.

**Comment by dm-mitre** [comment]
I think this is due to how python timedelta objects represent differences. Only the days value can be negative so a negative offset will be stored as a large positive number of seconds (with a negative offset). We'll have to code a fix to store days in timedeltas.
