### ISSUE TITLE
Unused variable in ability marked as requirement

### ISSUE THREAD

**Issue by jeyam93** [mitre/caldera#2935]
In the pre defined Adversary "Alice 2.0" is the ability "Account-type Admin Enumerator" included. 
Under Requirements it has listed backup.admin.ability which is used to set the variable $backup in the powershell Script. But this variable is nowhere used in this adversary, not even in the powershell script where it is defined. On the adversary view this ability is marked with a warning sign, stating that it has an unfulfilled requirement, because a value for backup.admin.ability is nowhere collected before in this adversary. Am I missing something, or is this requirement simply wrong so I can ignore it?

**Comment by elegantmoose** [comment]
Hey @jeyam93, so it actually is used in the adversary, but in a sort of sly (non obvious) way. In short, when this adversary was prototyped, it had issues with repeatedly compromising the same hosts, which was not desired. So, the authors, working with Caldera's limited pre/post condition fact system did what they could to put some guardrails to make it work. In effect, this fact is one of the facts the adversary and fact source will use to try to prevent repeat spawning of the agent on the same host. 

The fact (variable) is in the command so that it gets passed to the post action parsers. An implementation detail in Caldera, existing facts accessed in the parsers must be used in the action. Thus you get this (not ideal) hack of putting the fact in the command, even though not used by the command itself.

The fact/variable itself will actually get set in the parser if certain logic is hit (https://github.com/mitre/stockpile/blob/fe0c5b7bbd5dcdde4f90b5b6e493c2b0459d03e8/app/parsers/netlocalgroup.py#L71) and then be passed in to every follow on execution of the action (as the action will potentially fire on every new agent that is spawned).

Clear as mud?

**Comment by elegantmoose** [comment]
> I have been using facts and requirements as a way to set the order of abilities with the batch planner. For instance, I may want a specific ability that downloads a tool to be run before an ability that uses the tool, even if the first one does not create any information to be used by the second one.

This is correct approach. While the second ability is not using any info from the first ability, it does need the "state of the operation" that the first ability gets the operation too. So, essentially you store a Fact that acts as a boolean flag that the denotes that the tool is present.

**Comment by elegantmoose** [comment]
> Is this behavior (requirements need to be in the command or they will always fail) documented?

Its implied, not explicit. We should note.

**Comment by elegantmoose** [comment]
> Also, what you explained in your 3rd paragraph isn't clear to me, but it might be a more elegant solution than just setting a useless variable as I do. I'm not sure how the parser (which operates after an ability) is able to influence the requirement check (before the ability) though, I'll try and understand that.

Its the same approach you are doing, its just the same ability/parser will create the requirement/dummy fact. Its useful because the same ability will be hit many times in same operation because new agents are spawned start from first ability in adversary profile.

**Comment by elegantmoose** [comment]
@jeyam93 Im going to close this one. Please reopen if need to.
