### ISSUE TITLE
Wrong time format in event logs of operations

### ISSUE THREAD

**Issue by koncentrat11** [mitre/caldera#2966]
Whenever I export the event logs of an operation, the time in the "operation_name" seems correct, but all the others are off by 2 hours, e.g., "operation_name": "Test (4/27/2024 4:13:00 PM", and "operation_start": "2024-04-27T14:13:04Z". The right time is the one in the "operation name", and is aligned with the time of the VM running Caldera. How to fix?

**Comment by guillaume-duong-bib** [comment]
The web interface displays time in your local timezone, a.k.a. `UTC+2` for you, but the times are stored in `UTC`.
The reason why the event logs has `"operation_name": "Test (4/27/2024 4:13:00 PM)"` is because when you restart an operation, the current time gets appended. Since it's only a string `(name = ma.fields.String(required=True))` and not an actual time `(start = ma.fields.DateTime(format=BaseObject.TIME_FORMAT, dump_only=True))`, thus it will not be updated to any timezone once set.
