### ISSUE TITLE
Remote connection to the caldera server http://ipcaldera:8888 does not log in

### ISSUE THREAD

**Issue by cris1198** [mitre/caldera#3021]
I set up the boiler server on a Debian machine, I want to connect to the server from another PC but when I access http://ipremotecaldera:8888 through the web it cannot log in, it stays there hanging, how can I solve it?

**Comment by elegantmoose** [comment]
See if the docs on server config help: https://caldera.readthedocs.io/en/latest/Server-Configuration.html#configuration-file

**Comment by elegantmoose** [comment]
@cris1198 did you pull 5.0 or master? 

*Try pulling down master and see these notes: https://caldera.readthedocs.io/en/latest/Server-Configuration.html#configuration-file

**Comment by elegantmoose** [comment]
Apologies for late reply.

**Comment by Ch1l3n0** [comment]
I ran into a section in the Caldera documents that describes this type of behavior when the app.frontend.api_base_url is left at its default setting. If you look at the developer tools, network tools, there's a failed 302 redirect as your browser tries to access the default http://localhost:8888. The docs say: 
_The value set for `app.frontend.api_base_url` is used to configure the Caldera v5 Vue UI when the Caldera server is started with the --build flag. It has been observed that in some situations the default configuration values can cause the UI to appear unresponsive due to misrouted requests. This mainly occurs when the server is running on a host different than the UI is being accessed from. In these cases, the value should be changed to the appropriate URL for the UI to route requests to._

**Comment by uruwhy** [comment]
@cris1198 Can you confirm whether or not updating `app.frontend.api_base_url` fixed your issue?

**Comment by ns0r** [comment]
I too have this problem, and modifing the app.fronted.api_base_url config parameter made no difference.

**Comment by uruwhy** [comment]
> I too have this problem, and modifing the app.frontend.api_base_url config parameter made no difference.

@ns0r If you open up the developer console on your CALDERA login page and attempt to log in, what console error(s) are you seeing?

**Comment by uruwhy** [comment]
> I too have this problem, and modifing the app.frontend.api_base_url config parameter made no difference.

@ns0r Did you modify the configuration file while CALDERA was still running? If so, any manual changes in the yaml file will be overwritten when the server stops. You can confirm this by double-checking the contents of the config file when the server isn't running.

**Comment by ns0r** [comment]
I was able to fix my problem by changing the VITE_CALDERA_URL from http://0.0.0.0:8888 to http://<ipaddr>:8888 in the /plugins/magma/.env file.  This fixed the login problem.  However the app still isn't looking right.  It can't see any agents, etc.

**Comment by uruwhy** [comment]
> I was able to fix my problem by changing the VITE_CALDERA_URL from http://0.0.0.0:8888 to http://myipaddress:8888 in the /plugins/magma/.env file, and doing a --fresh --build. This fixed the login problem. However the app still isn't looking right. It can't see any agents, etc.

Can you send a screenshot of what your login page looks like? 
My fresh install looks something like this (no agents currently beaconing in, no previous operations):
<img width="1666" alt="Screenshot 2024-09-24 at 08 58 14" src="https://github.com/user-attachments/assets/d37188b7-ea99-4507-9f73-680b4330655c">

**Comment by elegantmoose** [comment]
reopen if issue still persists.
