### ISSUE TITLE
Enumerating the Administrators group of testwin7x64-2.test.com failed

### ISSUE THREAD

**Issue by leaqi** [mitre/caldera#32]
Hostname: testwin64
Command Line: powershell -command -
StdIn: [[powerview]] Get-NetLocalGroupMember -ComputerName testwin7x64-2
StdOut: 

why did this?below jobs:
 {
    "_id": "5ae9caed463377156c0d95e7",
    "agent": "5ae9839746337714403fda76",
    "action": {
      "rats": {
        "hostname": "testwin64",
        "name": 5536,
        "function": "execute",
        "parameters": {
          "command_line": "powershell -command -",
          "stdin": "[[powerview]] Get-NetLocalGroupMember -ComputerName testwin7x64-2"
        }
      },
      "result": {
        "pid": "2724",
        "stdout": ""
      }
    }

does hostname differ matter?

**Comment by hf-mitre** [comment]
Sometimes (on newer versions of Windows) the RAT needs to be running under domain accounts to enumerate group membership.  There should be a log message that states something to this effect if CALDERA's initial implant was running from a local account.   

This could be the case if the operation was started with creating a new RAT under the system account.  If this is the case, can you try starting the RAT so that it runs under a domain accoutn?  This can be done by entering credentials into the web interface, logging into the account on the starting host and selecting active user, or manually starting a RAT (copy it to the system and run it) before the operation and selecting the existing RAT from a list. 

We're working on letting CALDERA recognize this situation and automatically try to create a new RAT under a domain account, but we're trying to decide between doing some small fixes or doing a larger overhaul with more features.  The workaround right now is to make sure that the first RAT that starts is running in the context of a domain account.

**Comment by qq854051086** [comment]
Thank you very much for your project, and I've had the same problem with the following hint: I'm the commander running with administrator privileges under the domain user:

WARNING:app.logic.planner:Action Breakdown:
WARNING:app.logic.planner:    2: GetAdmin
WARNING:app.logic.planner:    1: GetDomain
WARNING:app.logic.planner:    0: WMIRemoteProcessCreate
DEBUG:app.logic.planner:Processed 3 plans
INFO:app.operation.operation:Planning time took: 0.04640351800000175 seconds
INFO:app.operation.operation:Running step get_admin
WARNING:app.operation.operation:Failed to parse with error: 'Unexpected Data in return: 

ComputerName : win8x01
GroupName    : Administrators
MemberName   : WIN8X01\Administrator
SID          : S-1-5-21-2376237030-2384050761-3293327795-500
IsGroup      : False
IsDomain     : False

ComputerName : win8x01
GroupName    : Administrators
MemberName   : S-1-5-21-1496744726-519298014-436046814-1115
SID          : S-1-5-21-1496744726-519298014-436046814-1115
IsGroup      : False
IsDomain     : True

ComputerName : win8x01
GroupName    : Administrators
MemberName   : TOPSEC\Domain Admins
SID          : S-1-5-21-2128254543-2934281151-1798086486-512
IsGroup      : True
IsDomain     : True

ComputerName : win8x01
GroupName    : Administrators
MemberName   : TOPSEC\guestuserx01
SID          : S-1-5-21-2128254543-2934281151-1798086486-1103
IsGroup      : False
IsDomain     : True

**Comment by qq854051086** [comment]
Thank you very much. I've solved this problem because I deleted domain users once on my computer. The easiest way to do this is to reconfigure the agent computer.
