### ISSUE TITLE
For sandcat 54ndc47 OSX error "flag provided but not defined: -group"

### ISSUE THREAD

**Issue by kwestin** [mitre/caldera#391]
When running "while true; do curl -sk -X POST -H 'file:sandcat.go' -H 'platform:darwin' http://localhost:8888/file/download > /tmp/sandcat-darwin && chmod +x /tmp/sandcat-darwin && /tmp/sandcat-darwin -server http://localhost:8888 -group my_group; sleep 60; done "

This error appears:

flag provided but not defined: -group

If I remove "-group my_group" I get the +beacon log, but data not appearing in agents

**Comment by privateducky** [comment]
This is a core/plugin misalignment. 

When using the bleeding edge code (latest master) you'll want to ensure the core code and all plugins you use have the latest master code pulled, otherwise you'll (likely) get errors. 

Two ways you can do this:

1. Re-clone the core code (recursively) 
2. Go into each plugin and checkout master, pull latest and (depending on your OS) do a hard git reset (git reset --hard origin/master).

**Comment by privateducky** [comment]
closing as answer should be correct.
