### ISSUE TITLE
Saving Adversaries in Firefox doesnt seems to work

### ISSUE THREAD

**Issue by wearenotsecure** [mitre/caldera#469]
I have noticed that when i am creating a new adversary using Firefox and click Save it doesn't work . The  page reloads as you would expect after clicking Save but the new adversary doesn't get created ( doesn't show up in the list) .  When doing the same using Chrome it seems to work fine. 
Firefox version being used : 68.0.2 (64-bit)

Not a big deal , mentioning just in case anyone else having similar issues.

**Comment by privateducky** [comment]
Thanks for dropping this here; right now we're only "officially" supporting the Chrome browser, so no testing has occurred elsewhere. This is mainly due to a small team supporting the tool and we wanted to pick a single GUI to limit support. That said.. if you want to add a patch for browser-compatibility, we'll definitely take it!

**Comment by wearenotsecure** [comment]
I would love to be able to create a patch and help you out however I have
zero coding experience .
