### ISSUE TITLE
can't run caldera.py

### ISSUE THREAD

**Issue by shgabay30** [mitre/caldera#54]
C:\Caldera\caldera-master\caldera>python caldera.py
Traceback (most recent call last):
  File "caldera.py", line 16, in <module>
    from app import server
  File "C:\Caldera\caldera-master\caldera\app\server.py", line 10, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

C:\Caldera\caldera-master\caldera>

**Comment by hf-mitre** [comment]
This was very likely caused by the failure you experienced in #53 .  `pip` never finished processing the `requirements.txt` so PyYAML was never installed.  See my comment on #53.  Pull down the latest changes and try `pip install -r requirements.txt` again.  If `pip` doesn't encounter any errors, PyYAML should get installed.  Good luck :)
