### ISSUE TITLE
Permission Denied on Start

### ISSUE THREAD

**Issue by lordoflannister** [mitre/caldera#55]
Whenever I attempt to start the server usign docker-compose up, I receive two issues in the Traceback:
             1) FileNotFoundError [Errno 2] for /opt/caldera/caldera/app/../conf/settings.yaml. The file is 
                 settings.yaml.default by default. 
             2) PermissionError [Errno 13] for the same file. 

I attempted to rename the file to settings.yaml, however I still received the permission denied error when doing so. I am running on centOS.

Any help is appreciated.

Thanks

**Comment by hf-mitre** [comment]
Don't believe that we've ever tried to get the Docker option working on centOS.  

First off, check that the directory being used permission's allow it to be written to. If SELinux is enabled, I think there's a good chance that it might be the cause due to the Docker bind-mount here: https://github.com/mitre/caldera/blob/master/docker-compose.yaml#L24 . This creates a mapping between the a path on the OS and the path in the container, so, when CALDERA sets up it's config directory it will also show up on the host's filesystem -- this means that if you make a change, rebuild the image, stop and destroy the old container and start up the new version it will retain the same configuration (it will get it from the centOS host filesystem). 

To test it out you can try deleting the 'volumes' section on the 'server' docker-compose service (lines 23-24 in docker-compse.yml)  and try to bring it up--the conf directory will not be present on the centOS host's filesystem in this case.  Depending on your use case, you probably want that config directory to stick around (keys and certs for HTTPS live in there)--in which case, you'll likely want to add the volumes section back in and add ':z' or ':Z' to the bind mount.  This will modify the volume's selinux label though, so you'll want to read up on what the option does first: https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label
https://prefetch.net/blog/2017/09/30/using-docker-volumes-on-selinux-enabled-servers/ 

Disclaimer: I've never tried to get Docker working alongside SELinux before, but this is where a few minutes of googling got me.

**Comment by lordoflannister** [comment]
Thanks!

**Comment by wietze** [comment]
For other people running into this issue who DON'T have SELinux installed:
I managed to fix this issue by changing the group of the `./caldera/conf` folder to `docker`, i.e.:
```
sudo chown -R `whoami`:docker ./caldera/conf
```
