### ISSUE TITLE
domain and connected agents not showing up. 

### ISSUE THREAD

**Issue by comemangu** [mitre/caldera#72]
I've installed CALDERA on a CentOS 7 box. It's connected to a Windows DC with 2 Windows 7 boxes. The agent and conf files have been placed in the necessary directory. I've tested that the Windows boxes cane be reached from the CentOS box. However, when creating a new network the domain does not show up and the agents do not register under  connected agents.

**Comment by cl-mitre** [comment]
Two quick things to try -

1) Verify that the CentOS box can be reached from the Windows boxes (connections originate from the target hosts, so if they can't reach out due to a firewall or something, everything hangs)
2) Verify that the conf files reference the proper IP, and that the agent is running (you can run it manually using *cagent.exe debug*, which might give you more information about its status)

Let me know if the problem persists after checking these two things.

**Comment by comemangu** [comment]
Thank you! When I imported the VM, it changed the IP address. I needed to update the conf files to reflect the change.
