### ISSUE TITLE
Trying to create a new step but the Copy step interferes with it, not sure why

### ISSUE THREAD

**Issue by trallgorm** [mitre/caldera#81]
I'm attempting to create a new attack technique, and it works, but only if I don't have the Copy step enabled. Here are the conditions for my step:

```
preconditions = [("rat", OPRat),
                   ("share", OPShare({"src_host": OPVar("rat.host")}))]
postconditions = [("excel_g", OPExcel({'host': OPVar("share.dest_host")}))]
preproperties = ['rat.executable', 'share.share_path']
postproperties = ['excel_g.macro_file_location']
```

And here are the conditions for the Copy step.

```
preconditions = [("rat", OPRat),
                     ("share", OPShare({"src_host": OPVar("rat.host")}))]
postconditions = [("file_g", OPFile({'host': OPVar("share.dest_host")}))]
preproperties = ['rat.executable', 'share.share_path']
postproperties = ['file_g.path']
```

If I enable the copy step, my step never gets attempted. Why is that?

**Comment by cl-mitre** [comment]
Although it's hard to tell for sure without more information, the reason why CALDERA isn't running your step along with the copy step is likely due to CALDERA's planner not recognizing that it would gain enough value from running the step for running the step to be selected. The exact reason for this is hard to tell, but two things that might help diagnose this are as follows:

1) Check to make sure that excel_g is used by another step in the adversary (CALDERA will occasionally ignore steps if it doesn't gain anything from running them).
2) Verify that the step's value is high enough (your custom one). You can do this by manually assigning a value by adding this `value = 10` to the step just before the conditions and properties.

If neither of these seem to make any progress, let me know and we can troubleshoot more.
