### ISSUE TITLE
Caldera server doesn't start

### ISSUE THREAD

**Issue by perra22** [mitre/caldera#811]
I'm trying to install Caldera on CentOS machine. When i do:
> python3 server.py

the bash return this error:

> DEBUG:root:Agents will be considered untrusted after 15 seconds of silence
DEBUG:root:Uploaded files will be put in /tmp
DEBUG:root:Serving at http://0.0.0.0:8888
DEBUG:app_svc:Loading plugin: caltack
DEBUG:app_svc:Loading plugin: chain
DEBUG:app_svc:Loading plugin: gui
DEBUG:app_svc:Loading plugin: mock
DEBUG:app_svc:Loading plugin: sandcat
DEBUG:app_svc:Loading plugin: ssl
DEBUG:app_svc:Loading plugin: stockpile
DEBUG:app_svc:Loading plugin: terminal
WARNING:app_svc:Ensure you have installed the PIP requirements for plugin=terminal
Traceback (most recent call last):
  File "server.py", line 87, in <module>
    main(app=app, config=cfg, services=app_svc.get_services())
  File "server.py", line 52, in main
    loop.run_until_complete(init(app, config, services))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "server.py", line 34, in init
    await app_svc.load_plugins(config['enabled'])
  File "/home/upo_1/caldera/app/service/app_svc.py", line 113, in load_plugins
    plugin = Plugin(name=plug)
  File "/home/upo_1/caldera/app/objects/c_plugin.py", line 18, in __init__
    module = import_module('plugins.%s.hook' % self.name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/upo_1/caldera/plugins/terminal/hook.py", line 6, in <module>
    from pyfiglet import Figlet
ModuleNotFoundError: No module named 'pyfiglet'

but i've already installed all the pip requirements. 

Thanks for the help!

**Comment by privateducky** [comment]
if you're running against bleeding-edge (latest master) you'll want to do a re-clone. 

we pushed up several changes over the past few days, including the addition of a c_plugin module (which converts plugins into objects in the backend code). I can see in your stack trace your code is using that new module, so odds are, your plugins are out of sync with the core code. 

most likely cause: you either cloned the repository while we were pushing this change up yesterday OR you did a git pull during our push up yesterday.

**Comment by privateducky** [comment]
(most of the time) we recommend you use the latest stable version -- but as long as you don't mind the occasional oddity, like above, using the bleeding-edge code will give you all the latest/greatest stuff we're working on. we aim to do new stable releases every 6-8 weeks.

**Comment by privateducky** [comment]
on second thought... I'm running a new python3 test, to validate the above, and I think there is something we introduced. give me a few minutes to check this out...

**Comment by privateducky** [comment]
ok - everything above I mentioned is good context - but you did find a bug as well!

**The fix is in**: https://github.com/mitre/caldera/pull/812. Let me know if you have any other issues there. 

**Extra context on this**: the pyfiglet import error (from your stack trace) was thrown because caldera is now looking at disabled plugins - along with enabled plugins - when you start the application. it'll look at each plugin in the plugins/ directory and try to ensure it can be loaded. if not, it'll throw a warning log for you to do a pip install on that individual plugin's requirements.txt. 

each plugin can have it's own requirements.txt file, so if you want to use a specific plugin, you'll want to navigate to it's root directory and do that pip install. the terminal plugin was the one complaining about the import in your case. 

**the bug**: when I added this code yesterday, I should have allowed the server to start if there were missing imports for disabled plugins, instead of a hard fail.

**Comment by perra22** [comment]
Thank you for your answer and your advices. I'll let you know if I have any other issue.
