### ISSUE TITLE
get_admin fails when run from a SYSTEM account

### ISSUE THREAD

**Issue by trallgorm** [mitre/caldera#82]
I actually found this issue previously in https://github.com/mitre/caldera/issues/77 and thought I fixed it by running it as admin. But now I can see that's still an issue because we're trying to get privilege escalation to work via service vulnerabilities(service_manipulation(sc file replace)), which elevates the RAT (shows up red) BUT the RAT now uses the SYSTEM account, from which get_admin fails. So if you use that method to elevate your RAT no other admins can be enumerated other than the ones you have on the current machine, meaning lateral movement is not possible if you use the built in privilege escalation method.

**Comment by hf-mitre** [comment]
@trallgorm in case you didn't see my note on #77, get_admin is failing because of the permissions configured for remote SAM access on the host being enumerated. 

On Windows 10 the default permissions are that only administrators are allowed to do this, though in earlier versions of windows it was much more open.  If you let the get_admin step continue to fail, CALDERA should eventually blacklist the action from the elevated RAT and then try again from the unelevated RAT--however this will probably fail as well if the user context of the unelevated RAT is not an admin on the target machine. 

https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-restrict-clients-allowed-to-make-remote-sam-calls 

I'm not sure what the best solution is for this.  To avoid having it fail multiple times before trying alternate RATs, we could try raising the value of get_admin to get CALDERA to execute it before it attempts privilege escalation.  We might also be able to dynamically reduce the value of failed actions so they wouldn't be retried before equivalent actions running from different RATs / hosts would be attempted. Though this doesn't solve the problem of not being able to figure out admin group membership. 

For windows 10, we need to figure out another way to do remote admin enumeration, or figure out a way to make guesses about where we can laterally move when remote SAM access is locked down.

**Comment by trallgorm** [comment]
@hf-mitre I'm sorry you are entirely correct, I did not see your note. To those having the same issue, my workaround was to go to each victim machine, go to Local Security Policy > Local Policies > Security Options > Network access: Restrict clients allowed to make remote calls to SAM > Edit Security > Add Domain Users and SYSTEM and apply.
