### ISSUE TITLE
[Question] Custom Code for Use by Adversaries

### ISSUE THREAD

**Issue by lordoflannister** [mitre/caldera#91]
So far the base application is working well, though I've run into a bit of a roadblock. I'd like to include both ATT&CK steps and my own code for use by a custom adversary, but I don't see any mechanism to do so. Am I missing something, or is this functionality not included? If not, is there any intention to include this in the future?

Thanks!

**Comment by cl-mitre** [comment]
Just to verify, when you refer to _ATT&CK steps_ you mean the built-in techniques, and your _own code_ refers to various arbitrary console commands you want to execute through Caldera? If so, this is doable by creating your own custom step, and configuring it to run your arbitrary commands either through command line or PowerShell. If not, I think the capability you are looking for is here, but I need more specifics in order to help you put everything together.

**Comment by lordoflannister** [comment]
That's correct - I would like to be able to run my own, custom steps - though for whatever reason, I was not able to find the custom step functionality. Any help is appreciated; this is an excellent project and is incredibly  useful. Thank you for your quick response!

**Comment by cl-mitre** [comment]
The process of creating and integrating custom steps is documented here:
https://caldera.readthedocs.io/en/latest/add_technique.html#adding-a-new-step. If you still have questions after perusing this, feel free to ask and I'll see if I can't help clear them up!
