### ISSUE TITLE
Vm images of framework

### ISSUE THREAD

**Issue by ghost** [mitre/caldera#97]
Hello,
I would like to use this software, but I have similar issue to the one described here:
https://github.com/mitre/caldera/issues/11

I was wondering if there are some working vm images of the server and an agent so that i could create an operation which includes lateral movement.

**Comment by cl-mitre** [comment]
Sadly, we don't currently have any available VM images for the server or agents. That being said, the new release of CALDERA we've been working on includes a simulation environment that can be used to play around with the interface and capabilities a bit more, which may meet your use case.

**Comment by workandresearchgithub** [comment]
For the Windows client, I used Windows 10.  The domain AD was built on Windows Server 2012R2.
All these I built in VMware Player, and used the Bridged network setting.
Caldera server is running on CentOS 7.x.
I could provide the VMimage, but since it's around 12gig I'm not sure I could upload it here.

Plus, it's not necessary as the install is simple if you follow these instructions.  Take a bit over 10 minutes after you install the CentOS:

[Caldera 0.3.0 - Installation.pdf](https://github.com/mitre/caldera/files/3024398/Caldera.0.3.0.-.Installation.pdf)

As far as the client install, I copy CAgent.exe and the RAT (cratermain) directly to the c:\temp directory, and start them manually by opening a CMD window (run as Administrator):

c:\temp\ CraterMainWin8up.exe

Then I open another CMD window (run as Administrator):

cagent.exe debug

You'll want to disable Windows Defender and Windows Firewall, and any other security controls you have installed, at least until you verify everything works.  Once you have everything working, you can start tightening things up.
